### ISSUE TITLE
HTTP system type not working with DIRECTV SHEF commands

### ISSUE THREAD

**Issue by SgtSlaughter16** [CommandFusion/iViewer-For-Android#10]
Im trying to get the http commands set up for DIRECTV box control. I know the TCP ones work fine but I haven't been able to get HTTP ones to function so far at all. I tested them in the browser and they work fine. 
Example: 
HTTP command: 192.168.1.2:8080/remote/processKey?key=menu 
TCP command: GET /remote/processKey?key=menu HTTP/1.1\x0D\x0AHOST: 192.168.1.2:8080\x0D\x0A\x0D\x0A 

The system properties for the HTTP one are the exact same as the ones for TCP with the exception of "HTTP" being selected as the protocol. I even tried changing the Heartbeat mode from "Replay" to the others and still couldn't get it to work with HTTP command...Again putting this in the browser address to test shows it functions fine. 

DIRECTV's SHEF commands are located below in case you want more info on them.
http://www.sbcatest.com/TechUpdates/DTV-MD-0359-DIRECTV%20SHEF%20Public%20Beta%20Command%20Set-V1.0.pdf 

my asv file should be here: http://db.tt/GfvtdRxP
my gui file should be here: http://db.tt/wOiKxRCu

**Comment by jarrodbell** [comment]
FYI, when you create an issue, the labels to attach are on the right of screen. Milestones are under the issue name.

**Comment by SgtSlaughter16** [comment]
Jarrod,

yeah i see them there now but they were not an option to add when I was creating the issue at all. The right side of the issue box is blank and there is no way to select which "milestone" either...

**Comment by jarrodbell** [comment]
Interesting, must be an option only visible to project administrators until the issue is posted... strange though!

**Comment by fpillet** [comment]
The dropbox link was very helpful, as it highlighted a number of pitfalls (redirections, spaces in URLs, and backslashes in pathnames). Think this has been fixed for buil 81. Jase, please reopen this issue if you still see it when we release build 81.

**Comment by SgtSlaughter16** [comment]
Okay will do. did you see anything specific I should of changed to be 100% sure it should work or should I just try again and report back.

**Comment by fpillet** [comment]
Several issues were causing problems:
- gzipped content returned by a webserver (in this case, dropbox) was mishandled
- space in URLs were mishandled
- redirections were mishandled
- Backslashes in paths were possibly causing the issue too. Look at your themes, you'll see that newtheme2 uses Images\button-round-large-a-white.png and Images\button-round-large-a-black.png. I'm going to test this & fix as needed.

**Comment by SgtSlaughter16** [comment]
backslashes....i remember that problem from the older beta long ago. had to go in notepad and change them all to a certain way, but that was b/c it was throwing errors when trying to load.

anyway ill just try it on the new beta when its released and go from there. as always let me know if you want me to test something specific on my end here.

**Comment by SgtSlaughter16** [comment]
This issue is still present in build 81. 

in regards to how the HTTP settings should be set up so I know it is right can either of you comment on if it matters in the "HTTP System properties" which "Heartbeat Mode" is set to?
Also in the actual HTTP command value does it matter if its "http://192.168.1.2...." or just "192.168.1.2:...." ??
I ask b/c I didn't know if the command is under an HTTP System if the value still requires the "http://" or if that is automatically placed in front of whatever you have in the value box. 
I test these commands by going to my web browser and verifying that "http://192.168.1.2:8080/remote/processKey?key=menu&hold=keyPress" in my laptops web browser results in the command being preformed as intended on the DirecTV box.

the TCP one listed in the original issue post works fine here. the initial press of it takes a little longer to register on the unit but after the first one is registered it is instant and normal as it should be.

**Comment by jarrodbell** [comment]
Your command value should be whatever comes after the URL (which is set as the system hostname/ip address).

So the system IP should be (no http:// at the start):
192.168.1.2

Command value:
/remote/processKey?key=menu&hold=keyPress

Heartbeat should be disabled (none).

**Comment by SgtSlaughter16** [comment]
still didn't work. let it sit and pressed it multiple times no luck. When doing it in the browser address bar on my laptop the command results in the box returning a response back as described in the SHEF pdf in my OP. I dont know if that has anything to do with this not working or not though.
The file thats returned incase you haven't looked at the pdf in the OP has the following:
{
  "hold": "keyPress",
  "key": "menu",
  "status": {
    "code": 200,
    "commandResult": 0,
    "msg": "OK.",
    "query": "/remote/processKey?key=menu&hold=keyPress"
  }
}

btw what would be the reason for having heartbeat set to reply mode in the tcp system?  that one works somewhat at least but im a little lost on some of the actual options available in the guidesigner. the only reason i have the one with TCP command settings is b/c someone with an iphone let me see their gui and what they had to test.

**Comment by SgtSlaughter16** [comment]
can this be reopened of is it something on my end setting it up?

**Comment by fpillet** [comment]
I missed something important in your GUI that causes the HTTP issue. Since you defined a system address for your HTTP system (192.168.1.2) you shouldn't replicate the IP / port information in the value you "write" to the system with your command. In other words, your command value should be:

/remote/processKey?key=menu

(side note, I noticed that your command value has an extra space at the end, you may want to remove that as well)

**Comment by SgtSlaughter16** [comment]
http://db.tt/G0yeQxej

Thats the link to the full folder images and all, gui I posted in the images loading issue thread and it still has the same issue still by the way.

If you look just above your post here I already tried removing the IP/port information from the command value and it didn't resolve the issue either. I even posted the information of the return response I get when I do it in a web browser address bar.

**Comment by fpillet** [comment]
Thanks. In the GUI you sent, the IP address of the HTTP system is 192.168.12. This won't work, you forgot a dot.

**Comment by SgtSlaughter16** [comment]
haha DUH. sorry I can't believe I missed that!

anyway still doesn't work with the change in IP to 192.168.1.2 for the gui. Left everything else the same except that, and it didn't work. 

I dont know if it has to do with the return response the box sends out but If so I listed the contents of the file in the post a few above just incase that could be part of it...

like I said I can do the command request(shown in a previous post 7 above here) in the web browser on my phone or  computers and it functions fine...

**Comment by fpillet** [comment]
Think I identified the issue at hand! Running some tests, but should be all set for next build

**Comment by SgtSlaughter16** [comment]
oooo looks like we have this working to an extent here in the latest issue 83!!!

It currently has a significant delay in the processing the command compared to the response that happens when I do it on my computer's address bar. But it definitely works now. I didn't try messing with Heartbeat or any thing else to see if those would make a difference at all.

**Comment by fpillet** [comment]
There shouldn't be a delay, I tried it here and it definitely executes the command immediately. A good test to check for any networking issue with your android device is to type the URL in your device browser's address bar, and check the timing.

**Comment by SgtSlaughter16** [comment]
yeah its my device that causes the delay here for some reason. my phone in the address bar of it has a delay too yet my laptop is near instant response. So thats on my end.

**Comment by fpillet** [comment]
It's possible that you have a general networking issue with your device, which could explain all your problems with downloading GUI's images as well, something we've never had an issue with

**Comment by SgtSlaughter16** [comment]
its connected via wifi never had any issue downloading anything or any network issue. I do have a semi advanced network here with Gig router, and Gig switch with a TON of things networked in and QoS set up but never had an issue here on this device...
