### ISSUE TITLE
crash 116

### ISSUE THREAD

**Issue by MichaelHartmann** [CommandFusion/iViewer-For-Android#100]
For reasons not known to me the version 116 crashes (after a few seconds) . In the remote debugger cannot see be seen what function is affected. Samsung GT-I9001 Firmware 2.3.6

**Comment by fpillet** [comment]
Hi Michael, please make sure you check out the notifications and click them to send the crash report to us, otherwise we can't find out what's crashing. Thanks!

**Comment by MichaelHartmann** [comment]
Do you mean "iViewer Settings" -> "Error Reporting" -> "Your Email Address"?

**Comment by fpillet** [comment]
No, when you get a crash the software shows a notification (swipe from the top of screen), to ask you whether you want to send a crash report. The report then gets sent to us where we can investigate it.

**Comment by MichaelHartmann** [comment]
There seems to be no crash. iViewer terminated by itself. The function "onGUISuspended" is not called. Once WIFI switch off, iViewer works.

**Comment by fpillet** [comment]
Please try http://www.commandfusion.com/download/iViewer-beta-117.apk (which fixes the UDP / onGUISuspended issues you reported) and let me know if this still happens!

**Comment by fpillet** [comment]
To install from your device, simply use this link: http://bit.ly/cfbeta117

**Comment by MichaelHartmann** [comment]
The error must do have with the feedback. Regex "\ x06 \ x10 \ x04 \ x20 \ x00 \ x17 [\ x00-\ xff] {10} \ X0F \ x0b [\ x00-\ xff] {3} ([\ x00-\ xff]) ([\ x00-\ xff])". "Although seems operation is not met, the calculation "Transform" "value \* 256" is called. And then the program was terminates. Delete is "value \* 256" everything is OK. But the calculation should not be called. This error is encountered only in the build 116 and 117. The build 113 was OK
Unfortunately, the function "onGUISuspended" is called when even if the portrait to "landscape" to "portrait" or vice versa.

**Comment by fpillet** [comment]
This is valuable information, thank you.

Ah yes Android is a bit special, the application "pauses" during rotation. Thanks for the info, going to fix this as well. New release soon.

**Comment by fpillet** [comment]
Crasher on math evaluation is fixed in build 120

http://bit.ly/cfbeta120

**Comment by MichaelHartmann** [comment]
it is now OK
