### ISSUE TITLE
Does anyone have same feedback issue

### ISSUE THREAD

**Issue by u7310330** [CommandFusion/iViewer-For-Android#102]
I can't get feedback from  the Legrand system but it works on Ipad and iphone.
does anyone know what different between these two system setting.

Wilson

**Comment by fpillet** [comment]
This is  too vague, please provide more information. We need some description of what data is going through, what the feedback items are, etc. Ideally, a simplified GUI that exhibits the issue. But realistically, any information about the data and the processing you're applying will help identify the issue.

Thanks for the report.

**Comment by u7310330** [comment]
Hi Florent,

I find-out what cause crash.
in monitor system
Regex *2*(\d)*95##
when i set value for digital join 8951 = {{if([@s895]==0 and [@s896]==0,1,0)}}
in iOS it is no problem but in Android it will crash.
if i remove one of  {} it is not crash in Android but in iOS will not get the status.

Hope it is useful.

**Comment by fpillet** [comment]
Thanks for the additional information. FYI, the pattern is invalid. In regex, "_" means "zero or more times" but it need to be preceeded with something. I think what you really wanted to express was "._2._(\d)._95##"

**Comment by u7310330** [comment]
Hi Florent,

Sorry when i submit forget to check it. I missed typing at Regex it is  /_2/_(/d)/*95/#/#  ( / to other side) 
 the backslash cannot shows on this web

**Comment by rohanvd** [comment]
Hi. I just posted a new issue (109), but I think it may be the same issue seen here.

**Comment by fpillet** [comment]
Should be fixed in build 129, please give it a go!

**Comment by u7310330** [comment]
Hi Florent,

I found it may cause this problem.
![mistake](https://f.cloud.github.com/assets/1747919/332042/c7891ba2-9c11-11e2-942b-a86bde7ed771.png)

i had deleted the space and it was working.

Hi rohanvd, you can check it and test it.

Wilson
