### ISSUE TITLE
Possible Screen Rotation Bug

### ISSUE THREAD

**Issue by GregSoli** [CommandFusion/iViewer-For-Android#103]
Setup: Nexus 7 OS v4.2.2

This may or may not be a bug but thought I'd mention it in case it should work differently.  The screen size for this tablet is 1280x800 but the actual usable space is 1280x735 (in landscape mode).  If you load a project that uses the 1280x800 resolution when the tablet is in the default position (Camera left/buttons on top) it will load fine - besides cutting off the top/bottom slightly - but the rotation of the GUI doesn't work if you flip the tablet over.  If you load the tablet in the upside-down orientation (Camera right/buttons on bottom) the project will load and look right but once you flip it over the GUI rotates and will not rotate back.  Shrinking the vertical resolution down to accommodate for the system bar fixes the issue.  I have not tried it in portrait mode.

Update:  It doesn't just happen with oversized screens.  My optimized screen size will eventually hang if rotated several times in a row, at which point the GUI will still function but won't rotate anymore.  Also, on occasion the screen will rotate into portrait mode ( I only have landscape defined in my GUI and no items on the portrait page), clipping the app on the 1280 pixel width down to 800 pixels, and the GUI will hang and require restarting.

**Comment by GregSoli** [comment]
After some more testing, it appears that when you only have one orientation defined the problem is significantly worse - to the point where it won't really rotate most of the time.  If, however, you have both a landscape and portrait orientation defined the app will rotate fairly regularly but will crash when repeatedly rotated.  Perhaps the single orientation issue is hanging on the occasion when the landscape orientation gets displayed in the portrait orientation as described above.

**Comment by fpillet** [comment]
Think I got it fixed for next build
