### ISSUE TITLE
TCP System Bug

### ISSUE THREAD

**Issue by GregSoli** [CommandFusion/iViewer-For-Android#104]
Setup: Nexus 7 OS v4.2.2

If you reset a system connection by using CF.setSystemProperties("systemName", {enabled:false/true})  the system will lose it's IP address.  You can verify by calling CF.systems['systemName'].address and it will return "".  If however you set the address with the enable property as such - CF.setSystemProperties("systemName", {enabled:true, address:'systemAddress'}) the system will connect every time.  

I have on occasion seen this happen when the GUI starts but it is easiest to reproduce as shown above.

Also, in debugger, if you look at the system the address will show as long as it's valid but the Remote and Local ports will always show 0, even if you set them using the above logic.  I'm using Chrome (26.0.1410.19 beta-m) on a Windows 7 64-Bit machine.  All of this works fine on an Apple iPad.

**Comment by fpillet** [comment]
Is your system defined in guiDesigner using a canonical name or an IP address?

Thank for the report!

**Comment by GregSoli** [comment]
Canonical name.  I believe the problem happens with a standard IP as well.
 I will try and report back.

On Thu, Mar 7, 2013 at 6:11 PM, Florent Pillet notifications@github.comwrote:

> Is your system defined in guiDesigner using a canonical name or an IP
> address?
> 
> Thank for the report!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/CommandFusion/iViewer-For-Android/issues/104#issuecomment-14592718
> .

## 

Greg Soli
Audio Advice, Inc.
704-614-2574

**Comment by GregSoli** [comment]
It happens with a standard IP address as well.

**Comment by fpillet** [comment]
Fixed for next build. Thanks!
