### ISSUE TITLE
Carriage Return Not Recognized Bug

### ISSUE THREAD

**Issue by GregSoli** [CommandFusion/iViewer-For-Android#105]
Setup: Lexus 7 OS v4.2.2

Serial strings on buttons or text elements don't recognize the Carriage Return ( \r or \x0D) but do recognize a Line Feed (\n or \x0A).  This works properly on Apple devices.

**Comment by fpillet** [comment]
Hrm this issue was supposed to be fixed. Thanks for the heads up. Are you using text wrapping?

**Comment by GregSoli** [comment]
I am on labels but buttons don't have that option.  I did a replace in JS
that substitutes a \n for the \r and it works properly.  On Apple devices
it works properly with either.

On Thu, Mar 7, 2013 at 6:12 PM, Florent Pillet notifications@github.comwrote:

> Hrm this issue was supposed to be fixed. Thanks for the heads up. Are you
> using text wrapping?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/CommandFusion/iViewer-For-Android/issues/105#issuecomment-14592741
> .

## 

Greg Soli
Audio Advice, Inc.
704-614-2574

**Comment by fpillet** [comment]
Fixed for next build. Thanks!
