### ISSUE TITLE
sliderval behaviour issue

### ISSUE THREAD

**Issue by rohanvd** [CommandFusion/iViewer-For-Android#107]
Hi.

Have been using version 103 for a fair while. This issue has arisen when trying to move to versions 120 & 121.

I have a number of sliders that pass [sliderval] to javascript functions (ie at OnDrag, On Release), which worked fine previously. Feedback from the device being controlled then updated the join allocated to the slider value displayed.

In the later builds, the [sliderval] value passed is the current (ie most recent feedback value assigned), rather than the new (On Press, On Drag, On Release) value. This means the slider does not work to control the device unless "Simulate Feedback" is active (which makes it flicker between the feedback value and the simulateded feedback value).

Does not occur with the current iPad iViewer.

**Comment by fpillet** [comment]
You're absolutely right, this is an oversight. Fixed for next build. Thanks!

**Comment by rohanvd** [comment]
That was quick !
