### ISSUE TITLE
Very minor html rendering curiosity

### ISSUE THREAD

**Issue by rohanvd** [CommandFusion/iViewer-For-Android#108]
Hi.

I've got a weather section that loads a TXT file from the Aus Bureau of Meterology in an HTML window (in this case from "http://www.bom.gov.au/fwo/IDW12300.txt").

I notice that on a Galaxy Tab 10.1, it always loads with a white background, but on a Nexus 7 it always loads with a transparent background.

Presume it's due to some difference in the default browser on the device.

Not a big deal, just thought I'd mention it in case people need to consider it to plan for consistency.

**Comment by fpillet** [comment]
Interesting find (and I think that we will find more subtle differences between devices as we get the product tested on more devices). Will have a look at this - want to make sure that the behavior is consistent accross devices and accross platforms.

**Comment by fpillet** [comment]
Fixed for next build. Thanks!
