### ISSUE TITLE
{{ XYZ . . .[join] }} crashes

### ISSUE THREAD

**Issue by rohanvd** [CommandFusion/iViewer-For-Android#109]
Hi.

I've found that creating a function with a math expression than includes the [join] token in the {{  }} makes the Android iViewer crash. Does not happen on iPad version.

**Comment by rohanvd** [comment]
Just reading back other cases - I think this may ne the same as Issue 102

**Comment by fpillet** [comment]
Thanks for the report, we're investigating the issue!

**Comment by fpillet** [comment]
Fixed in build 129, please give it a go!
