### ISSUE TITLE
Javascript Doesn't Run Without Debugger

### ISSUE THREAD

**Issue by GregSoli** [CommandFusion/iViewer-For-Android#110]
Hi Florent, 

Setup: Nexus 7, OS 4.2.2

I just installed the latest Beta - 132, some of the Javascript in my project isn't working properly any more unless I am using debugger.  The project worked fine in the previous version 131 (backed down to test).  Basically, my CrestronMobile script won't work but a very basic script that just sets a text field will.  Not sure what it is since it works fine when debugging.

Let me know if you want me to send you my GUI.

**Comment by u7310330** [comment]
I have same issue.

Also, i have 4 list in one screen using CF.setProperties to hide and to show the list that is mean i have 4 layer on the screen but the first layer area always cover next few layer. so, at next few layer of button in that first list area cannot working it.

Wilson

**Comment by fpillet** [comment]
Sorry about this - you can revert to http://bit.ly/cfbeta131 which is still on the server. The latest changes related to reloading Javascript on GUI reload seem to have issues in release builds (our debug builds worked fine!)

Thanks for the heads up

**Comment by fpillet** [comment]
I identified the issue: files with a space in their path name (i.e. space in name or subfolder name) won't load. Fix on the way.

**Comment by fpillet** [comment]
Build 133 is up.

**Comment by u7310330** [comment]
Hello Florent,

Have you testing multi-list for example, i have 4 layer on the screen. if the first layer area large than others. The top list always cover next few layer even it's hided. so i am only be able to see the list.

Hope you can understand what i am described it.

Wilson

**Comment by MichaelHartmann** [comment]
Hallo Florent,

The build 133 works only in debugging mode. The Build 122 works well. It seems that Java Script will does not start.

Regards Michael

**Comment by MichaelHartmann** [comment]
Hallo Florent,

with the Build 135 is all OK.

Regards Michael
