### ISSUE TITLE
Can not perform js on iViewer beta 133

### ISSUE THREAD

**Issue by NhaThongMinh** [CommandFusion/iViewer-For-Android#111]
My Script run very good on iViewer beta 129 but can not on iViewer 133. I also tested with demogui on github.

**Comment by fpillet** [comment]
Can you give su more information about this? Copy-pasting the <script> part of the .gui file would be a good start. We need to know how many scripts you are using, and their names in case the name encoding was the issue.

**Comment by NhaThongMinh** [comment]
This is part of my Gui file:
![Part Gui File](https://f.cloud.github.com/assets/3970491/303330/882d7c54-9622-11e2-9877-64fb041f6217.PNG)

**Comment by fpillet** [comment]
I'm not 100% sure about what's not working for you there. Which device are your using, what Android version is it running? Did you upgrade Android version between build 129 and build 133? Did you change anything to your JavaScript between these two builds?

**Comment by u7310330** [comment]
Hello Florent, 
I have 2 phone the Kernel version are different bata133 is work on Kernel 3.0 but not works on 2.6.35

other question is have you testing multi-list for example, i have 4 layer on the screen. if the first layer layout area large than others. The top list always cover next few layer even it's hided.

Hope you can understand what i am described it.

Wilson

**Comment by fpillet** [comment]
Wilson, would you mind creating separate support issue for separate problems? Hijacking a bug to report another one may result in your issue not being handled - it's easy to oversee

**Comment by u7310330** [comment]
Hello Florent,

I have created the new issue. about js cannot works on bata133. I have 2 phone the Kernel version are different one is Kernel 3.0 other is 2.6.35. but bata133 only work on Kernel 3.0 version

Wilson

**Comment by fpillet** [comment]
Ok so I can confirm that JS support is broken on Android 2.x. Working on a fix. Thanks for the report!

**Comment by fpillet** [comment]
Fixed for next build
