### ISSUE TITLE
multi-list only Top Layer working

### ISSUE THREAD

**Issue by u7310330** [CommandFusion/iViewer-For-Android#112]
My question is I have multi-list only top layer can works.  for example, i have 4 layer on the screen each layer i using list when i click button i will hide other 3 lists. if the first layer layout area large than others. The top list always cover next few layer even it's hided.

Wilson

**Comment by fpillet** [comment]
What do you call "layer"? Are you using subpages, or are you using CF.setProperties() to hide / show lists?

Can you email me a sample GUI that exhibits your issue?

**Comment by fpillet** [comment]
Fixed for next build. Thanks a lot for the example GUI!
