### ISSUE TITLE
Slider Indikator Text

### ISSUE THREAD

**Issue by MichaelHartmann** [CommandFusion/iViewer-For-Android#113]
Slider Property -> Aktiv -> Indikator Text -> X and Y has no effect

**Comment by fpillet** [comment]
Fixed for next build (was an issue with autoscaling). Thanks!

**Comment by MichaelHartmann** [comment]
Hello Florent,
is it possible for a developer license to get for my Android phone?
Regards Michael

Von: Florent Pillet notifications@github.com
Gesendet: ‎4‎. ‎April‎ ‎2013 ‎16‎:‎13
An: CommandFusion/iViewer-For-Android iViewer-For-Android@noreply.github.com
Cc: MichaelHartmann wischenhofen@t-online.de
Betreff: Re: [iViewer-For-Android] Slider Indikator Text (#113)

Fixed for next build (was an issue with autoscaling). Thanks!

**Comment by fpillet** [comment]
Hi Michael, sure please make sure you are using the latest build from Play Store (#166) then point to this GUI: id.commandfusion.com which will help you get your android device ID into your account on our web site. Apply for a free license, don't forget to let me know the name of your account on our site, and I'll activate it.

**Comment by MichaelHartmann** [comment]
Hi Florent,

Thank you. My account ist "wischenhofen@t-online.de".

Regards
Michael

Am 03.06.2013 00:43, schrieb Florent Pillet:
