### ISSUE TITLE
indication of system connected fails

### ISSUE THREAD

**Issue by tuliomenezes** [CommandFusion/iViewer-For-Android#116]
indication of system connected fails
make a button with same digital join of system connected. Jump to another page and the button is no longer updated with its digital join value.

you can test with this project and hercules: https://dl.dropbox.com/u/23807396/tulio_android_b1_test4.zip

Android MID TM7009, V2.3.4, beta build 136

**Comment by fpillet** [comment]
Fixed for next build. Thanks!

**Comment by tuliomenezes** [comment]
just a small remark: if you set "simulate feedback", the button will not have the correct value after a page shift.
tested with beta build 139
