### ISSUE TITLE
subpage background scaling

### ISSUE THREAD

**Issue by n2hifi** [CommandFusion/iViewer-For-Android#117]
Build 140, Nexus7, Positioning set to "Scale to fit screen".
On some of my subpages the background is not scaling (i.e. full scale) while thet content inside the subpage does scale.  it's random, like if i close the subpage and reopen it is fixed then I do it again and it is wrong.  I haven't figured out a way to consistently replicate.

**Comment by fpillet** [comment]
Can you provide with a minimal example of this? We can't seem to be able to reproduce the issue. Thanks!

**Comment by n2hifi** [comment]
I have several “widgets”(subpages) that opens a new subpage when you swipe  them.
‘correct’ is what it is supposed to look like.
‘incorrect’ is what I have been getting randomly.
Note my page was set up for 1280x800 and is now scaling to fit (no matter what I set Positioning to in Project Properties).

I have the whole thing in dropbox if you want to look at it I can share it.

Mark Olsen, CTS
Design Engineering
Cignal Systems, Inc.

**Comment by fpillet** [comment]
Yes if you could share your test GUI with me, would be appreciated. You can email me directly (florent at commandfusion dot com) with details to access it. Thanks!

**Comment by fpillet** [comment]
Fixed for next build. Thanks for the test case!
