### ISSUE TITLE
Button on subpage into list don't work

### ISSUE THREAD

**Issue by sdomotica** [CommandFusion/iViewer-For-Android#12]
If I insert a subpage into a list, and this subpage cointain a button, it don't work.

**Comment by jarrodbell** [comment]
What exactly doesn't work? Please be more specific.

**Comment by sdomotica** [comment]
I have a top bar navigation with jump command and javascritp function for each button.
The topbar is a subpage into a list object for a horizzontal scrolling and for have a lot of page jump
The buttons are unclickable.
See the picture for explain my situation

http://dl.dropbox.com/u/13367262/List%20Properties.jpg

Bye
Sandro

**Comment by fpillet** [comment]
This issue is weird, we have a test GUI that uses a similar technique (header subpage containing buttons) and which works just fine. Except that it is vertical, not horizontal. Is it still failing with build 81 ? Does it work on iPad ?

**Comment by sdomotica** [comment]
I send you the GUI that work on iPad but not on my Samsung Galaxy Tab 10.1 with 
81.

Bye

Sandro

**Comment by fpillet** [comment]
Your GUI works fine here. Reopen the issue if it's still not working with next build and we'll investigate with you for issues specific to your device.

**Comment by sdomotica** [comment]
Stil don't work. On 83.

This appen on my Galaxy Tab 10.1 and Kindle Fire.

I attach here for other pubblic test.

Bye
Sandro
