### ISSUE TITLE
input field reverse text automatically 

### ISSUE THREAD

**Issue by NhaThongMinh** [CommandFusion/iViewer-For-Android#120]
I'm run iViewer beta 146 on Android 2.3.6 with , Input field always reverse my text input.
Example : when I type "46" it's show "64" and cursor turn to left automatically.

**Comment by fpillet** [comment]
We believe that this issue has been fixed in latest build 148 now available, can you confirm? Thanks!

**Comment by NhaThongMinh** [comment]
Thanks. Input field's working very well now.
