### ISSUE TITLE
"Caching assets..." doesn't stop

### ISSUE THREAD

**Issue by rohanvd** [CommandFusion/iViewer-For-Android#122]
Hi.

Just upgraded to latest version (150) after getting prompt.

Now when starting, if "Preload Assets" (and "Show Preload Progress") is ticked, the "Caching Assets . . ." notification stays up continuously. Was not an issue on previous build used.

If preloading is turned off, it seems to load and work OK (although I haven't given them a good workout since).

**Comment by fpillet** [comment]
I think this issue is solved in build 151. Can you please give it a go? If it's still causing issues, please email me your GUI for investigation.

**Comment by rohanvd** [comment]
Thanks. All working fine in build 151.

**Comment by fpillet** [comment]
Thanks for testing!
