### ISSUE TITLE
WOL feature

### ISSUE THREAD

**Issue by Robertoh323** [CommandFusion/iViewer-For-Android#123]
Smartphone: 9300
Android version: 4.1.1

Problem: I have find a problem to use WOL command from my Android smartphone.
The same project and the same command work w/o any problem from iPad with iViewer 4 (...on the same network) and I can power on a videoconferenze system. 

regards
Roberto

**Comment by fpillet** [comment]
Modify your GUI to change the Port Origin value in guiDesigner for your WOL system to some value above 1024. Android is stricter is enforcing access to ports, and if your phone is not rooted, iViewer can't have a socket that touches ports below 1024 _on the device_. It can still send packets directed to port 9 of other devices on the network, of couse.
