### ISSUE TITLE
http system is not working

### ISSUE THREAD

**Issue by tuliomenezes** [CommandFusion/iViewer-For-Android#127]
I made a http system to control denon avr-1912
in iPad and iPhone works good, but in Android not.

Tested with:
CF beta build 153
Android MID TM7009, V2.3.4, with and without beta license
Rikomagic (clone) , V4.0.4, with and without beta license
https://dl.dropboxusercontent.com/u/23807396/denon_html_test.gui.zip

**Comment by fpillet** [comment]
Fixed for next build. In the meantime, ensure that either the variable part (the command value) of your command starts with a "/", or that the remote system address ends with a "/".
