### ISSUE TITLE
It is still possible to activate debug mode with encrypted zip file

### ISSUE THREAD

**Issue by tuliomenezes** [CommandFusion/iViewer-For-Android#129]
It is still possible to activate debug mode with encrypted zip file (it should not)
Despite the possibility, you cannot see JS, because it is still encrypted (another issue already reported)

Tested with:
CF 4.0.157
Android MID TM7009, V2.3.4
Rikomagic (clone) , V4.0.4
https://dl.dropboxusercontent.com/u/23807396/teste_enc.zip
https://dl.dropboxusercontent.com/u/23807396/teste_not_enc.zip

**Comment by fpillet** [comment]
Fixed for next build, thanks!
