### ISSUE TITLE
iViewer is "calculating" another uuid for device and license no longer works

### ISSUE THREAD

**Issue by tuliomenezes** [CommandFusion/iViewer-For-Android#132]
version .157 - license still valid
version .167 and above, license doesn't work anymore, guiDesigner shows another device ID.

please let me know if this new uuid will be valid. I will wait a definition before using "transfer license" for this new device ID

**Comment by fpillet** [comment]
Yes. There was an issue with device UUID calculation in versions prior to 167, it should not change anymore.
