### ISSUE TITLE
Port caching

### ISSUE THREAD

**Issue by n2hifi** [CommandFusion/iViewer-For-Android#133]
Is it correct behavior that when the "Reload GUI layout" box is checked you cannot load a layout from guiDesigner? Even if you select "Reload GUI" and have Upload Service turned on it loads it from memory on the tablet.

**Comment by fpillet** [comment]
No this shouldn't be the case. I assume you are using build 176. We're looking into this.

**Comment by fpillet** [comment]
Fixed for next build. Thanks!
