### ISSUE TITLE
HTTP request repeating

### ISSUE THREAD

**Issue by n2hifi** [CommandFusion/iViewer-For-Android#134]
I have a DirecTV device that can be controlled via IP.  I created a system with  HTTP protocol, IP address (192.168.111.14) and port(8080).  All other settings are default.

I then create a command with value "/remote/processKey?key=chanup" (channel up).  All other settings are default.  When I issue this command the DirecTV box jumps numerous channels instead of one.  This behavior is the same for all commands.  If I issue "HTTP://192.168.111.14:8080/remote/processKey?key=chanup" from the web browser on the tablet it works properly.  This behavior is consistent across multiple DirecTV boxes.

Nexus 7 Android version 4.3
 iViewer 4.0.176
 guiDesigner v2.6.0.602

**Comment by fpillet** [comment]
Ran some tests here with a button that triggers a command sending the HTTP request. So far, no repeats are seen. How do you trigger the command? Seems to me that the issue lies in the _way_ the command is being trigger (repeats) rather than the http system itself.

**Comment by n2hifi** [comment]
Problem with cut and paste is if there is something not quite right it copies and copies and copies...and all of the sudden you think it's a bug.  Sorry about that one.  Found it.
