### ISSUE TITLE
iViewer 177 has problems to remember downloaded file via internet link

### ISSUE THREAD

**Issue by tuliomenezes** [CommandFusion/iViewer-For-Android#137]
iViewer 177 has problems to remember downloaded file via internet link

how to test:
fill file url with www.iluflex.com.br/gui/interface_pro_v3.zip
check all options, hit back and wait loading
when load is finished, go to settings and turn off the options 1, 2 and 4 
hit back - the project should be remembered, but in V177, the Android loads again the file

in V.176 there is no problem

Tested with Galaxy Tab 3, Android v4.1.2 , without license

**Comment by fpillet** [comment]
Just pushed 4.0.178 which should fix this issue. Please confirm when you have a chance.

Thanks!

**Comment by tuliomenezes** [comment]
version 4.0.178 did fix the issue 
thanks
