### ISSUE TITLE
Image loading redux

### ISSUE THREAD

**Issue by n2hifi** [CommandFusion/iViewer-For-Android#138]
I noticed a new version came down google.play so now I am at 4.0.178.  It fixed the caching issue but I see another small one. When I upload it doesn't upload images on pages and subpages not currently displayed.  In other words if I do a 'reload GUI' and wait a few minutes it appears everything loads and all is good.  If I stop the 'Upload Service', any images on pages that were never opened while the upload service was running did not load and do not display.  It is only images, not buttons.

**Comment by fpillet** [comment]
Checking back on this issue, is it still happening with 4.0.185 released today? If yes, can you privately send me a test GUI ? Thanks!

**Comment by fpillet** [comment]
Thanks for your example, Mark. We were able to identify the source of the issue. Next build fixes it.
