### ISSUE TITLE
Unable to get past application submit screen 

### ISSUE THREAD

**Issue by mcsSolutions** [CommandFusion/iViewer-For-Android#15]
After install of beta, email address entered and credentials obtained by email.  When iViewer opened again same screen appears prompting for email and submit button.  If submit button is used then message appear that request already submitted.  Unable to get past Apply for Beta License page.

**Comment by fpillet** [comment]
This is normal, it's the only screen in this beta. Go to Settings, enter the URL of your GUI project and you'll be all set.
