### ISSUE TITLE
Join updates button image but not text on startup.

### ISSUE THREAD

**Issue by rohanvd** [CommandFusion/iViewer-For-Android#17]
I have a number of button on the startup screen to show the status of network connections to an iTach and a C-Gate server. They are set so that the inactive button is dark and the text says "disconnected" at startup. When the connection is made and the corresponsing join goes high a few seconds after starting, the button image switches normally to the active bright image, but the text does not change (ie the image changes from the inactive to active state, but the text from the inactive state remains).

If, however, you go back to that page from another, the buttons and text redraw correctly (ie both active version).

**Comment by fpillet** [comment]
How do you update the button when the connection is established?

**Comment by rohanvd** [comment]
The button join number is just associated with the TCP/IP connection in Systems.

The TCI/IP socket connects normally , and the join goes high/on.
The button image updates from the inactive version to the active version of the image for that button theme, BUT the button text does not change from the inactive version to the active text for that button (unless the page re-draws by returning to it from another page).

**Comment by fpillet** [comment]
Fixed for next build. Thanks for your feedback!
