### ISSUE TITLE
Slider number not updated by javacript

### ISSUE THREAD

**Issue by rohanvd** [CommandFusion/iViewer-For-Android#18]
I have some sliders for dimming lighting which can be adjusted directed on the UI, or can be updated by feedback which is parsed via javascript.

When adjusting via the UI, the slider and the level on the indicator text update fine.

When the slider is updated by feedback (ie parsed and set via javascript), the slider position/graphic updates, but the indicator text value does not.

**Comment by fpillet** [comment]
Good catch, thanks!

**Comment by fpillet** [comment]
Can you send me your GUI or a reduced sample that exhibits your issue?

**Comment by fpillet** [comment]
Found the issue. Fixed for next build. Thanks!
