### ISSUE TITLE
Images rendering as slightly differing colours

### ISSUE THREAD

**Issue by rohanvd** [CommandFusion/iViewer-For-Android#19]
Odd one. I have a number of buttons where the graphics were created from the same source (same blank blue button with different details superimposed). I scale them to exactly half size for CommandFusion (the original images were created for Pronto).

On the iPad iViewer they look fine 9and the same apart from the superimposed details)

On the Android iViewer they render in slightly different colours, some look the normal blue, others have a greenish tinge. Scaling has not changed.

**Comment by jarrodbell** [comment]
Can you upload your GUI somewhere so we can download and test it on both iOS and Android to compare?

**Comment by fpillet** [comment]
Try viewing these images on your Android device without iViewer. I bet that what you're seeing comes from a difference in gamma table / LCD quality, as iPad display is a very high quality one.

**Comment by rohanvd** [comment]
iPad and Android versions of Config file for download here:
http://www.rohansplace.com/Data/CF_Projects.zip
I've also included screen captures from both the iPad and Android tablets, showing the variable button colour on the Android render (ie not likely a display issue).
Thanks (and great work so far, by the way).

**Comment by rohanvd** [comment]
Issue no longer seen after updating to vet version 81. Good work.
