### ISSUE TITLE
TCP systems

### ISSUE THREAD

**Issue by sdomotica** [CommandFusion/iViewer-For-Android#21]
In version 80 I had 4 system in system manager TCP type with flagged mantein connection

They worked with the error on startup command solved by Florent.

In version 81, I can use only two system no more.

Bye
Sandro

**Comment by fpillet** [comment]
Can you elaborate on the issue you are seeing? Only two systems connect, not the two others? Can you send your GUI for evaluation? Thanks

**Comment by fpillet** [comment]
How does build 83 behave for your regarding this issue?
