### ISSUE TITLE
iViewer Icon image on Kindle Fire blurry

### ISSUE THREAD

**Issue by SgtSlaughter16** [CommandFusion/iViewer-For-Android#22]
kindle fire
system version: 6.2.2_user_3205220
Milestone 82

Icon used for the iViewer app on the kindle fire is very blurry(wrong resolution?) in the "apps" page and even more so when its on your home screen in the recent apps wheel. 

*I know this is a minuscule bug but I didn't see it reported and figured it can't hurt. If you want to just focus on "function" for now then just let me know and ill ignore things like this that pop up till later in the process.

**Comment by fpillet** [comment]
This is a known issue, due to Kindle Fire only showing a high resolution icon when downloaded through Amazon App Market.
