### ISSUE TITLE
Swipe Gesture attached to image is not manipulating digital joins correctly

### ISSUE THREAD

**Issue by mcsSolutions** [CommandFusion/iViewer-For-Android#23]
When moving finger left or down on an image no discrete event is send back to server.  The events are generated for right and up.

**Comment by fpillet** [comment]
Can you elaborate ? Is this somehow related to Gestures ? Need more information for this issue please, thanks.

**Comment by mcsSolutions** [comment]
An image where the image URL is formed from string join from the server of size 200 x 150 exists on the viewer design.  When using a gesture as swipe motion in some direction over the image the Apple Viewer returns the digital join that corresonds to the gesture in each up, down, right , left directions.  The gesture manager defines only the Phase: Begin to produce the digital join.  On the Android viewer a gesture of left or down has never produced a digital join back to the host.  The right and up occur, but are not reliable.

**Comment by jarrodbell** [comment]
So to sum it up, join value changes (in this case digital) are not being sent back to the Control System when attached to Swipe Gestures (specifically left and down swipes).

**Comment by mcsSolutions** [comment]
That is correct.  Never observed success on any left and down and most often the other two directions also provided no input back to control system.

-----Original Message-----

**Comment by fpillet** [comment]
Fixed for next build. Thanks for your feedback!
