### ISSUE TITLE
CARRIAGE RETURN IGNORED ON ANDROID STRING RENDERING

### ISSUE THREAD

**Issue by mcsSolutions** [CommandFusion/iViewer-For-Android#24]
Line control used for Apple string CR (0C hex) to cause string break to next row start of line is ignored on android.

**Comment by fpillet** [comment]
You should be using \x0A for line breaks. What are you using and where is it not being rendered correctly?

**Comment by mcsSolutions** [comment]
The Apple iViewer implemention uses x0C in string joins from the server to update text box entries on iViewer.  The same implementation on the Android results in a different rendering where the x0C is ignored by the Android viewer while on Apple results in return ot start of next line.
