### ISSUE TITLE
GUI DOWNLOAD SEQUENCE NOT ROBUST

### ISSUE THREAD

**Issue by mcsSolutions** [CommandFusion/iViewer-For-Android#25]
The process of downloading the GUI into android is not well synchronized with designer.  Often when starting multiple attempts are required with iviewer crash reported in status bar with request to upload the crash. Sometimes iViewer placed message box asking to edit the user settings.   The Honeycomb back arrow is used to get away from the cycle of iViewer prompts and that results in the iViewer crash message.  After selecting iViewer again from Apps then the Activity light on designer appears as desired and the iViewer application starts normally.

**Comment by fpillet** [comment]
Several startup crashes on the device have been solved (at least, those that were reported to us via the notification system on the device -- hopefully, you did so). Please wait for the next build and try again, things should be smoother for you.
