### ISSUE TITLE
TEXT WRAPS RATHER THAN TRUNCATES

### ISSUE THREAD

**Issue by mcsSolutions** [CommandFusion/iViewer-For-Android#27]
A text box is defined as W 450 H 80.  When text of more charcters than will fit in one line of 450 pixels the text wraps to the next line even though the wrap property of the text box is unchecked.  The expected behavior is that the text will truncate and text appears on the second and subsequent line only following the line break (0A) character.  This behavior was not tested on Apple.  If this is the designed behavior, then what is the scenario for which the wrap propery of the text box will yield different results?

**Comment by fpillet** [comment]
Fixed for build 82. Thanks!
