### ISSUE TITLE
GUI DOWNLOAD IGNORES VIEWER RELOAD SETTING

### ISSUE THREAD

**Issue by mcsSolutions** [CommandFusion/iViewer-For-Android#28]
Every time android viewer is started it attempts to download the design from upload service even though the Reload GUI layout setting is unchecked.  If the Upload service is running it will transfer the desgn with activity led active.  If the service is not running then the viewer does not immediately complete startup.

**Comment by fpillet** [comment]
Don't see this behavior here. The only case where activity could be seen in guiDesigner is when there are images missing and iViewer retries the download every time it starts again.
