### ISSUE TITLE
HOST TO VIEWER JOINS ARE NOT ALWAYS ACTED UPON IN VIEWER

### ISSUE THREAD

**Issue by mcsSolutions** [CommandFusion/iViewer-For-Android#29]
An emai inquiry was sent about the loss of image updates via serial URL joins and the reply was essentially that IPhone was busy.  Atttempts were made to both consolidate  joints into one TCP packet, to separte URL joins and add delays, to each update in its own TCP packet, to repeat TCP packet transmission.  The TCP activity has been monitored with Wireshark and packets are being delivered, but not always acted upon within viewer.  The same situation exists for both IPhone and Android.  Because of this unreliabilty there needs to be a method by which a viewer can acknowledge receipt of a join command or that a host can send request for status of all or selective joins.  It is important that the host and viewer maintain consistent information.

**Comment by fpillet** [comment]
Can you provide us with more data about this, in particular the packet sequence that you see delivered to the device, and what happens on iViewer side? There is no reason join updates are lost, neither on iOS nor on Android. If you see the same behavior on both sides, then the issue may be elsewhere.

**Comment by mcsSolutions** [comment]
The issue could not be recreated when trying to collect the data to demonstrate the problem.  I believe the essential issue was the connection was dropped as indicated by debug messages in the control system and the lost connection would not allow delivery of join information to the viewer.  I have no insight why the viewer dropped the connection.

I have not been able to deploy the application to a control system other than the one from which the gui is downloaded.  In essence the designer .gui file has System Manager with URL xyz and port w and the .gui file is downloaded from development computer URL abc port d.  The viewer continues to try to connect to system at abc port w following download of the .gui from abc port d.  What is the proper configuration to design on a development computer and deploy on a different control system target?

-----Original Message-----

**Comment by fpillet** [comment]
This makes no sense to me. There is no rewriting of the system addresses, can you provide us with a test GUI that exhibits the issue?

**Comment by mcsSolutions** [comment]
Quoting Florent Pillet 
reply@reply.github.com:

**Comment by mcsSolutions** [comment]
Discovered that control system is setup in properties and not in System Manager.  When set this way there is no issue for the GUI download and the control system being different IPs.

-----Original Message-----
