### ISSUE TITLE
Background setting flags are not yet being honored.

### ISSUE THREAD

**Issue by jarrodbell** [CommandFusion/iViewer-For-Android#3]
Currently, the GUI stays alive when in background until the OS decides to force-terminate it, if ever. In case you need to completely restart the application, go to the Applications manager in the device Settings and Force Close the iViewer application.

**Comment by SgtSlaughter16** [comment]
confirmed this as well.
I caught this as well here looking at my history usage in systempanel app which shows apps active and using resources since i have monitoring on. after backing out of the iViewer it still showed it active for a long time which was eating away at the battery.

**Comment by jarrodbell** [comment]
Yup, this is one of the things listed in the beta documentation. Just added it here for tracking.
