### ISSUE TITLE
Buttons on subpage into list don't work

### ISSUE THREAD

**Issue by sdomotica** [CommandFusion/iViewer-For-Android#30]
Stil don't work. On 83. 
This appen on my Galaxy Tab 10.1 and Kindle Fire. 
I attach here for other pubblic test. 

http://dl.dropbox.com/u/13367262/florent7fire.gui.zip

The first 4 button are out of lists and they work.

The below. No

Bye
Sandro

**Comment by fpillet** [comment]
Oh this is a different issue than just "buttons don't work". This is related to buttons and lists, but turns out that actions defined on buttons weren't carried on when buttons were in list subpages. This has been fixed for next build, your GUI helped immediately nail the issue. Thanks!
