### ISSUE TITLE
Changing GUI file URL/Reload crash

### ISSUE THREAD

**Issue by SgtSlaughter16** [CommandFusion/iViewer-For-Android#32]
build 83

Changing the GUI File URL on my device has resulted in it crashing completely when it tries to reload the gui. The upload service was up running fine. As soon as you change the URL and press back to the actual GUI screen it tries to reload the new gui and crashes.
Re-opening the app causes it to open fine, and loads the last gui that was on that URL but pressing "Reload GUI" causes the app to crash instantly. Reopen the app again and hit reload gui and crash once again. This happens for a few times until one of the times when the app loads it gives you the "caching assets" progress bar and actually loads the new gui. 

After then the reload function works fine on that GUI's URL...
*Well I thought it did b/c the first time after the first load and I saw the button placement change to line up with my new gui it would reload on the button fine but now after loading the gui on the 2nd ip address too messing around with the reload button causes it to crash each time no matter what I've tried here...

I submitted crash reports to line up to this at the start a few times and one just before sending this in.

Note:
I have 1 laptop that has options for 3 GUI URL's since its connected via WiFi and via direct Cat6 cable if this makes a difference with the service at all...

**Comment by fpillet** [comment]
Excellent catch, it's crashing trying to tear down ongoing HTTP requests. Fixing it now, I'll make a new build available early next week.

**Comment by fpillet** [comment]
Temp workaround until we upload a new build: do at least one of those HTTP requests before pressing Reload GUI :-)

**Comment by SgtSlaughter16** [comment]
okay. makes sense completely there b/c the one time i loaded the gui and did NOT press any of the buttons and was just trying to replicate the issue going away was the time that it kept crashing. The ones where I pressed the HTTP command button stopped crashing after that now that you mentioned it.

**Comment by SgtSlaughter16** [comment]
Well scratch the Reload working fully as I change the GUI around press the HTTP button and reload and it just refreshes the same gui again...
If I have both "Reload GUI layout"  chacked then the reload button works perfectly. With that unchecked, even pressing the reload button it only refreshes the older gui. 
I was under the assumption those two options(Reload GUI layout & assets) I checked only were supposed to effect the app from reloading things on startup...

**Comment by fpillet** [comment]
You're a serial killer. Another good catch, there was a slight flaw in the reload logic (was not forcing the Reload GUI / Reload Assets flags before initiating the reload process). Fixed for next build as well.

**Comment by SgtSlaughter16** [comment]
haha no problem QA is my thing...

**Comment by SgtSlaughter16** [comment]
Reload button on the gui screen works perfectly now so far btw! no crashes and it reloads the gui each time

**Comment by fpillet** [comment]
Thanks for letting me know. I spotted a couple more crash cases thanks to the built-in crash reporting feature, will issue a build 85 ASAP
