### ISSUE TITLE
Rotation shows only CF logo and Reload GUI issue still.

### ISSUE THREAD

**Issue by xAPPO** [CommandFusion/iViewer-For-Android#33]
84 much better now than 83 re crashes...
 (see later comment)

However Rotating a GUI  shows CF logo only, reverting orientation shows same (previously startup page was displayed).  

If it's of interest Server shows cache time of GUI when accessed from iPad but not when accessed from Android. Android access is many times slower and server shows several 'green light' accesses over about 5 secs. iPad is near instant.  I wonder if first load hasn't completed fully.

Also Reload GUI appears to do nothing initially with no server activity  (read issue #6) but actually about 2 mins later I see a 'Loading GUI' dialog on screen and some server access but seems to hang there.  Have to force quit.

After 'Reload GUI' and whilst Android is displaying 'Loading GUI' permanently if you load a GUI from an iPad then  the Loading GUI dialog on Android disappears and is replaced by 'Preparing GUI' and then a blank screen  is displayed in both portrait/landscape. Sometimes crashes when rotated.   Actually just noticed that after about 2 mins this blank screen is replaced by correct GUI again but with 'Caching Assets' overlaid.   Seems to stick there though.   Looks like some really clogging server access maybe...

Caveat - this may not be an iViewer issue . This  is latest alpha build of ICS running on HP TouchPad - it is not a formal ICS build.  However it seems pretty good with most apps.

**Comment by xAPPO** [comment]
It seems it's a webpage link - to a cam image - I know they aren't yet supported but I think they actually need removing from the project.  That was causing the crashes and comms breaks .

However I do still get some blank GUI's after exiting Settings or when re-launching the app and 'Reload GUI' mostly doesn't seem to work - although occasionally it does very slowly .  I still get these long delayed Loading GUI messages and Caching Assets and maybe 90 seconds later it does display.

And even at startup I never see a DeviceID showing in the Server when loading GUI and no cache time displayed - and it does take a good 5 secs - is this all as expected ?  

After sleep CF always starts to blank screen, wont reload GUI and wont reconnect to system. Needs force quit.

 WiFi link is good and reinstates correctly after sleep for other apps.

**Comment by xAPPO** [comment]
Loaded beta 85 and things are much much better... great progress.   If the problems have gone I'll close this issue.

( I still don't see the device ID are cache time after the GUI load from the server though but that's not a worry )

**Comment by fpillet** [comment]
Yes the request that sends the UUID and cache time doesn't work well on Android, haven't had time to fix it yet

**Comment by fpillet** [comment]
Oh that was you with the touchpad. I fixed the crashes that I've seen occurring on your device, a couple good ones. Thanks for reporting!

**Comment by xAPPO** [comment]
Well done Florent,    the fixes seem to have done the job so I am closing this issue.

 ... it's getting there..

Kevin
