### ISSUE TITLE
Samsung Galaxy Nexus

### ISSUE THREAD

**Issue by dbs808** [CommandFusion/iViewer-For-Android#34]
Hello on a Samsung Galaxy Nexus running Ice Cream Sandwich 4.0.2 when you start iViewer and the "Apply for Beta License" window appears you cannot type in your email address. No keyboard appears by clicking anywhere on the window so you can't progress any further

**Comment by fpillet** [comment]
Thanks for your report. We have now had the occasion of testing on a real ICS device yet, but we'll look into this.

**Comment by fpillet** [comment]
Fixed for next build
