### ISSUE TITLE
Active Button style image not displaying

### ISSUE THREAD

**Issue by SgtSlaughter16** [CommandFusion/iViewer-For-Android#36]
http://db.tt/G0yeQxej

That should be my GUI folder saved from before. When pressing the buttons the "active" button images do not display at all whether I tap the button or hold it down the image stays on the "inactive" button.

Build #86
HTC EVO3D 2.3.4
Kindle Fire

**Comment by fpillet** [comment]
This is normal. Set your buttons to "Simulate Feedback" mode, or set a join other than 0 on your button their state will transition when the control systems reflects the d#=1 / d#=0 sequence to you

**Comment by SgtSlaughter16** [comment]
ahh DUH! simulate feedback check box did the trick there. 

Is there info on how to use the "Digital Join" box and what it does exactly?
