### ISSUE TITLE
Unable to get focus on the email field of the "Apply for beta license" page

### ISSUE THREAD

**Issue by jice** [CommandFusion/iViewer-For-Android#38]
Unable to get focus on the email field of the "Apply for beta license" page.
No keyboard appears.

Device Samsung Galaxy SII i9100
Android 2.3.5
Using Beta version 86

**Comment by fpillet** [comment]
Several people reported this. Not sure why this happens on some devices and not others yet. Investigating

**Comment by klyf** [comment]
I had the same problem in my ASUS TF101 Android 4.0.3. Reloading the "Apply for beta license" page and click very fast I could enter my e-mail, but again, the submit button was disabled. 
I tested in another android 2.2 tablet, and the apk file was not recognized.

**Comment by jarrodbell** [comment]
Android 2.2 is not supported.

**Comment by klyf** [comment]
How about android 4.0.3? Many people are complain about this same
problem! When are you planning fix it?

2012/3/26 Jarrod Bell
reply@reply.github.com:

**Comment by fpillet** [comment]
ASAP (next few days). We've been busy fixing issues on iOS, sorry.

**Comment by fpillet** [comment]
Fixed for next build
