### ISSUE TITLE
Registration code not working - page flips still disabled

### ISSUE THREAD

**Issue by Scaramush** [CommandFusion/iViewer-For-Android#40]
I added registration info for my Dell Strek 5 to test project, but when I try to browse some pages I saw "Unregistred device" message. My account is alex.skoropad[at]mtm.dn.ua

**Comment by jarrodbell** [comment]
Can you please open the .gui file in a text editor and copy/paste the  <devices> section here so we can verify you entered the license correctly?

Please also tell us what build of iViewer you tested with.

**Comment by Scaramush** [comment]
```
<devices>
  <device name="b57c468df0a6bd480d54ae471d1cbcb7352f0667">7AE2743F5FB3D11EDAA5A6A2A6A90C04</device>
  <device name="Development Device">CFF4264A8C47939197F42FFFF81AAE54</device>
</devices>
```

I use iViewer beta 85

**Comment by jarrodbell** [comment]
Those two devices are iOS devices (one is actually our own iPad, the other is your development iOS device).

You need to add your android device license in there. If you do not have one, page flips will not work.
