### ISSUE TITLE
IViewer does not work. Android (2.3) 

### ISSUE THREAD

**Issue by SmirnovEV** [CommandFusion/iViewer-For-Android#41]
Application does not work. application starts and then after 5 sec closes.

http://dl.dropbox.com/u/37086892/log.txt

**Comment by jarrodbell** [comment]
Please submit your crash logs, as documented in the google doc all beta testers must read. If you have already done so, please close this issue.

**Comment by fpillet** [comment]
What is your device? Apparently you have the "bad" build on Android 2.3, the same that is found in Android Emulator (either native of x86). This version of Android has a broken Webkit <-> Java bridge and iViewer can't run on it, sorry. You'll have to upgrade your OS, if your device maker provides one. It's a broken OS issue we can't do anything about.
