### ISSUE TITLE
IP Address / Hostname

### ISSUE THREAD

**Issue by MichaelHartmann** [CommandFusion/iViewer-For-Android#42]
Hello
Very good job.
Without Java Script it works fine. The greatest problem I have, that
in the system proerties not the host name, such as eg
"Name.dyndns.org". I can only enter the IP address eg "192.168.2.100".
Regards
Michael 
Info: Platform: Android, Version: 2.3.6.XXKQ7, Model: samsung GT-I9001, Device Name: samsung GT-I9001

**Comment by fpillet** [comment]
Hi Michael, can you elaborate on this issue? Sorry I'm late looking into this - In particular, I need to understand whether iViewer (from your point of view) can't resolve canonical names (name.dyndns.org) in systems set in guiDesigner, or if it's an issue with JavaScript.

**Comment by MichaelHartmann** [comment]
When I use the guide designers in the System Properties in the IP Address / Host Name "name.dyndns.org" enter, then the iPad is the IP telegram "standard query a name.dyndns.org" sent. And there is an appropriate response. With Android is not the case.

**Comment by MichaelHartmann** [comment]
This feature is very important to me.

**Comment by MichaelHartmann** [comment]
This feature is very important to me.
