### ISSUE TITLE
wifi trouble (continue of issue#39)

### ISSUE THREAD

**Issue by Scaramush** [CommandFusion/iViewer-For-Android#46]
Hi!

I'd test sending commands to hardware from iViewer for android. And found one problem in iViewer: if I launch iVierwer, reload GUI and try to send something - nothing worked (nothing sends from android device, I tested it with sniffer), but if I exit from iViewer after reloading (and stop it's process) and than launch it again - all commands sends. I think it's bug)

**Comment by fpillet** [comment]
This issue should have been fixed.
