### ISSUE TITLE
The "Page Timer" do not work.

### ISSUE THREAD

**Issue by MichaelHartmann** [CommandFusion/iViewer-For-Android#47]

**Comment by tuliomenezes** [comment]
You mean the timer on a page that fires a command? I have a small test, one page (not beta-licensed yet) and the timers work. 

Beta build 88, chinese tablet TM7009 (known also as LY-F1/F1S/F2)

**Comment by MichaelHartmann** [comment]
I send a small test project to "fpillet@gmail.com". Is it possible to produce in "github" attachments?.

**Comment by fpillet** [comment]
Fixed for next release - this was an issue with something internally crashing in this particular case. Thanks for the report and the test GUI !
