### ISSUE TITLE
GUI fails loading via Vpn

### ISSUE THREAD

**Issue by mgehrlein** [CommandFusion/iViewer-For-Android#48]
Hi,
on my Samsung Galaxy Nexus a simple GUI loads fine when I'm connected via Wlan, but fails loading when a Vpn  is active.

The error message is: length=4; index=4

Did anyone else have a similar experience?

Cheers,
Marcel

**Comment by fpillet** [comment]
Marcel,

Would you mind testing with a recent build? we just released build 122 which may have made things better with this.

**Comment by fpillet** [comment]
Fixed in build 131
