### ISSUE TITLE
heartbeats are sent only in ascii even with \x option

### ISSUE THREAD

**Issue by tuliomenezes** [CommandFusion/iViewer-For-Android#49]
I have a system that needs to send and receive a heartbeat in hex chars. With the iPad, the heartbeats are sent correctly in hex mode , when I use the notation \xHH. 

Eg. \xA5\x00\x00\xA5

When I test in my Android, this same information is sent in ascii. In Hercules I see the ascii \xA5\x00\x00\xA5, instead of hex digits A5 00 00 A5.

Android V2.3.4 , Tablet MID TM7009, beta build 88

**Comment by fpillet** [comment]
Fixed for the build that will come after #96 that we just released
