### ISSUE TITLE
Render GUI from top left (instead of centering)

### ISSUE THREAD

**Issue by jarrodbell** [CommandFusion/iViewer-For-Android#5]
There needs to be an option (once scaling modes are enabled) to change where the GUI should take its reference point from when rendering a GUI that is too large or too small for the current orientation.

For instance, when designing a GUI for kindle, 1024x600, there is a constant bar at the bottom of screen which takes up 20 pixels of height. This forces the GUI when designed for 600 height to lose part of the top and part of the bottom of the GUI as its centered before being rendered to screen.

If we were able to set reference point to top left, then only the 20 bottom pixels of the GUI would be lost, and makes it much easier to design for room in the bottom 20 pixels, allowing the same size GUI to work on any device that has the permanent status bar, and a device that uses hard buttons (and no on-screen status bar).

**Comment by fpillet** [comment]
Problem with this is that the permanent status bar, if any, may not be the same size on each device.

Really, there is no other good solution that to design for the actual usable screen size of the device you are targeting.

**Comment by jarrodbell** [comment]
Still would be nice to offer this as an option when we add various scaling options (stretch, maintain proportions, center, etc).

**Comment by fpillet** [comment]
Ok we'll see that in a later phase
