### ISSUE TITLE
feedback in loopback system doesn´t execute the command

### ISSUE THREAD

**Issue by tuliomenezes** [CommandFusion/iViewer-For-Android#50]
I have a physical system that captures hex digits, transform in a serial join (eg. 170) and runs a command in loopback system that contains the [@s170] to be matched in one of its feedbacks. 

One feedback in loopback system matches the command and then should set four analog joins (sliders) with a specific value.

The problem is that set of analog joins don´t  happen in Android. Same project in iPad works good.

Android V2.3.4 , Tablet MID TM7009, beta build 88

I will send to support the project and instructions to reproduce with hercules.

**Comment by tuliomenezes** [comment]
same behavior with Beta build 96

**Comment by fpillet** [comment]
Thanks to your GUI file I could fix the issue for the next release. Thanks!
