### ISSUE TITLE
Samsung Fascinate issue

### ISSUE THREAD

**Issue by Sanft** [CommandFusion/iViewer-For-Android#52]
I can seem to lock in GUI every time I load GUI then uncheck reload GUI. Then I go back to launch I viewer 4 app it still searches for GUI. Even though I have already caught GUI.

**Comment by tuliomenezes** [comment]
It happened to me also (chinese tablet MID TM7009) but in some moment it didn't happen anymore and I don't know what I've done different. 
For now, I dont have have the problem.

**Comment by Sanft** [comment]
I got it to work so this is how I got it to work. I Uploaded Gui then unchecked reload gui then had to hit the back button then the home button and launched Iviewer 4 again. Then it seemed to work great after that. Another way I did it was to uncheck reload gui and just hit reload gui and it seemed to work that way too
