### ISSUE TITLE
sometimes can't connect to a system if the wifi doesn't have internet access

### ISSUE THREAD

**Issue by tuliomenezes** [CommandFusion/iViewer-For-Android#55]
If the WiFi used to test the project on Android doesn't have access to Internet, the connection to a system doesn't happen in many occasions. 

When I start the iViewer, it is not possible to connect to a system (monitored via a digital join), sometimes it connects after a long period of wait.

If I connect the internet access to the WiFi router, the connection to a system is instantaneous, after restarting iViewer.

Maybe this behavior is because iViewer needs to have internet access to report the bugs to CF team.

Beta build 88, Tablet MID TM7900, Android V2.3.4, without license, System: Global Cache GC100-06,constant connection, RS232, port 4999

**Comment by tuliomenezes** [comment]
Change to iTach IP2SL (RS232 model), input license for the device, but the behaviour is the same.
Beta build 88, Tablet MID TM7900, Android V2.3.4

**Comment by tuliomenezes** [comment]
same behavior with Beta build 96

**Comment by fpillet** [comment]
Connection / reconnection issues have all been fixed in latest builds
