### ISSUE TITLE
webpagetool , no local page

### ISSUE THREAD

**Issue by MZorzy** [CommandFusion/iViewer-For-Android#56]
i use webpage tool (w) on a subpage (want load a local html page)

example code (cut):

  <subpage name="webtest" w="800" h="600" clip="1">
    <web x="5" y="5" w="790" h="590" j="0" title="0" back="0" forward="0" refresh="0" stop="0" url="./webhtml/index.html" />
  </subpage>

on android tablet i have :
"Loading http://./webhtml/index.html failed"

(on ipod iviewer load local index.html)

**Comment by fpillet** [comment]
Can you please cut down a simple project with reproducible case? This will speed up fixing the issue.

Thanks for reporting!
