### ISSUE TITLE
some button not shows and it is crash all the time

### ISSUE THREAD

**Issue by u7310330** [CommandFusion/iViewer-For-Android#57]
i using iviewer to control MyHome Energy management 
it work on iphone and ipad when i was loading to android (samsung GS2) the button does not shows.
I have try to rotation the phone sometimes it will shows button(not all of button) but sometimes it was not.
I can email my gui files for someone want testing it
my email : u7310330@gmail.com

**Comment by tuliomenezes** [comment]
I have the problem that some buttons are not shown when fliping pages. To solve this, I press the android settings button twice. Sometimes it is needed to press the android home button and call iviewer again (without killing it). After that, all buttons in the project are shown, until a new page flip. This problem changes its behaviour every time I add a new button or page in the project.

Android MID TM7009, V2.3.4, beta build 88
