### ISSUE TITLE
How to attach tags and milestones to an issue report?

### ISSUE THREAD

**Issue by tuliomenezes** [CommandFusion/iViewer-For-Android#59]
The CF team asked us to attach some tags and milestone to an issue report, but I cannot see how to do this.

Please let us know if it is really necessary since we cannot see the big picture. 
Eg. for me it could be a bug, but for you would be a HW problem or an expected behaviour.

**Comment by fpillet** [comment]
When reporting an issue, please make sure that you report the version of iViewer that exhibits the issue (as well as any info on regression - i.e. did it work before and is it broken now), the model and OS version of the device you are using, and any other relevant information.

Don't bother with tags & milestones for now, we'll sort the issues as needed.
