### ISSUE TITLE
Reload GUI from popup menu doesnt reload, just refreshes old GUI

### ISSUE THREAD

**Issue by jarrodbell** [CommandFusion/iViewer-For-Android#6]
When using the 'Reload GUI' button in page settings, it either failed to reload the updated project layout (which contained a smaller height GUI to allow for 20 pixel status bar on kindle) or failed to reload the bg image graphic (which was also 20 pixels smaller than the previously loaded image).

Reload GUI Layout and Reload GUI Assets were both turned on in the iViewer settings.

Force close and relaunch the app fixed the problem.

**Comment by fpillet** [comment]
Fixed for next build
