### ISSUE TITLE
Start delay inside an action group on a button is not been honored

### ISSUE THREAD

**Issue by tuliomenezes** [CommandFusion/iViewer-For-Android#60]
Start delay inside an action group on a button is not been honored. All commands are been executed immediately.

For reference, same project in iPad works good.

Android MID TM7009, V2.3.4, beta build 88

**Comment by tuliomenezes** [comment]
same behavior with Beta build 96

**Comment by fpillet** [comment]
Thanks for the report, fixed for next build!
