### ISSUE TITLE
iViewer not working with USB to Ethernet Dongle

### ISSUE THREAD

**Issue by deanholtwork** [CommandFusion/iViewer-For-Android#61]
I am using an Archos 101 G9 running Andriod 4.0.3 and iViewer beta 88

I have connected a USB to Ethernet dongle via a USB to Go lead to the Archos and I can web browse etc.

When running iViewer I can download GUI's to the tablet using the Ethernet connection but when I press buttons on the GUInothing happens at all. I can navigate around the GUI but not control anything.

Sometimes when re-enable wi-fi sometimes i have to force close iViewer then open it again to get the GUI buttons to do anything

iViewer works perfectly with the GUI i am using with a wi-fi connection

**Comment by fpillet** [comment]
Thanks for the report - we don't have a USB dongle here, but we'll check out what could happen that causes iViewer to not work properly with network bridging solutions. This may be linked to other known issues occurring when wifi is being turned off then on.

**Comment by fpillet** [comment]
Can you please give it a go with buiild 131, just released.
