### ISSUE TITLE
Disappearing buttons

### ISSUE THREAD

**Issue by rohanvd** [CommandFusion/iViewer-For-Android#63]
After initial GUI load, all buttons visible in portait mode.

Rotate to landscape and some buttons disappear. Rotate back to portrait mode and some of the buttons that were visible initially also disappear (sometimes on the second or third rotation)

Same issue seen on both a Nexus 7 and Galaxy 10.1.

Example video here -
http://www.rohansplace.com/Data/Buttons.wmv

**Comment by fpillet** [comment]
Can you verify whether this issue is still present with the latest build? If yes, can you attach a test GUI or email it to me? Thanks!

**Comment by rohanvd** [comment]
Hi. I’m out of town until next week. OK if I get back to you after that ?

Cheers, RvD.

Sent from Windows Mail

From: Florent Pillet
Sent: ‎30‎ ‎August‎ ‎2012 ‎3‎:‎44‎ ‎PM
To: CommandFusion/iViewer-For-Android
CC: Rohan
Subject: Re: [iViewer-For-Android] Disappearing buttons (#63)

Can you verify whether this issue is still present with the latest build? If yes, can you attach a test GUI or email it to me? Thanks!

**Comment by fpillet** [comment]
Of course, no problem

**Comment by rohanvd** [comment]
Hi.

Tried beta 96 on Galaxy Tab 10.1 and Google Nexus – problem no longer occurs.

Thanks, Rohan.
