### ISSUE TITLE
Screen rotation in Nexus 7

### ISSUE THREAD

**Issue by rohanvd** [CommandFusion/iViewer-For-Android#64]
If you load the GUI on Nexus 7 whilst in portrait mode, everything is OK.

If you reload the GUI whilst in landscape mode, screen keeps rotating to wrong orientation (including Android menu bar).

Example vid here -
http://www.rohansplace.com/Data/NexusRotation.wmv

**Comment by fpillet** [comment]
Fixed for next build

**Comment by rohanvd** [comment]
Thanks !
