### ISSUE TITLE
Problem reLoad GUI

### ISSUE THREAD

**Issue by Trikom** [CommandFusion/iViewer-For-Android#67]
We downloaded the demo version of iViewer for android.

We downloaded on a Samsung Galaxy S3.

We  loading the GUI using guiDesiner, It is the same at a iPad. OK?

The problem occurs when, after loading the complete GUI (images, assest, ..) Then we changed the settings to not reload. But, when we the application is closed and re-enter. Try load again, no matter how we place the configuration options.

If we leave active service, smooth reloads. But if we stop the service, the GUI do not works

**Comment by fpillet** [comment]
Should be fixed by the latest beta. Closing this bug, please reopen it if you still see it.
