### ISSUE TITLE
Remote Debugging doesn't work with Safari (Win 7)

### ISSUE THREAD

**Issue by tuliomenezes** [CommandFusion/iViewer-For-Android#68]
in beta build 96, I cannot connect to the device using Safari (5.1.5) on Windows 7. 
It appears the message: Javascript interface up and running, opening connection with iViewer and stops on this.

With Chrome (21.0.1180.83 m), I can connect but doesn't  see any event, the systems and joins don't have any information. 
It only appears: 

> Javascript interface up and running, opening connection with iViewer
> Established connection with iViewer
> Javascript starting up. iViewer version: 1.0 (#96-600a664)

Android MID TM7009, V2.3.4

**Comment by fpillet** [comment]
We have only tried the debugger connection from Chrome on Mac so far. Thanks for the additional testing on Windows - looking into this.

**Comment by fpillet** [comment]
I gave it a go:
- Safari on Windows is not supported by iViewer for Android right now. It's still using an old version of the WebSocket protocol (whereas Safari on Mac is up to date) and it seems that Apple is dropping Safari on Windows anyway.
- Chrome 21.0.1180.83 m works fine for me, but I'm on XP. Can you elaborate on what you don't see? Maybe attach a screenshot? I checked that I correctly see my Systems and Joins.

**Comment by tuliomenezes** [comment]
I used same project in iPad and Android. Tested with Chrome in Win XP and Win7, all with the same results: with iPad, I can see the Systems, Joins and the mixed log (feedbacks, button pressed, etc.). With Android, no information is showed. 
Please see the screenshots on: https://dl.dropbox.com/u/23807396/remotedebugging_chrome_ipad_x_android.zip

**Comment by MichaelHartmann** [comment]
Hallo Florent

Unfortunately it does not work for me. Windows7 how to Mac OS X 10.6.8. Neither Chrome nor Safari. JAVA script is not to start.

no logging at CF.log

e.g.
var KNXCommon = {
    setup: function() {
      try {
         CF.log (".........................

same as with "tuliomenezes"

Start without debugging Java Script runs  without problems

Info: Platform: Android Version: 2.3.6.XXKQ7, Model: Samsung GT-I9001, Device Name: Samsung GT-I9001

**Comment by curtdwar** [comment]
I had the same issue as the guys above. I tried debugging on...

Windows7: Chrome 21.0.1180.89 m
Mac OSX Lion 10.7.4: Safari 5.1.7 (7534.57.2)
Mac OSX Lion 10.7.4: Chrome 21.0.1180.89

Same as screenshots above. 

since beta 100, I now  get two issues. (let me know if they should be listed separate to this item)
1. No matter what port I choose for debugging, it is always telling me to use port 1024.
2. On all 3 systems listed above I get error "FORBIDDEN: this server only accepts websockets."

**Comment by fpillet** [comment]
Oops I think I broke debugging in beta 100. I'll issue an update within 24 hours. Thanks for letting me know

**Comment by fpillet** [comment]
curtdwar, what is your device / which version of Android is it running? I could reproduce your issue but under very specific circumstances only, so I wonder whether there is a correlation with your version of Android

**Comment by curtdwar** [comment]
Nexus 7, Android 4.1.1

**Comment by fpillet** [comment]
I have unbroken the debugger in the just release build #102. Please let me know how this works for you.

**Comment by curtdwar** [comment]
Debugging now working in Chrome in both windows7 and OSX Lion.

Still sits at 'opening connection with Iviewer' message in Safari. 

Thanks Florent. It's good to have debugging working again.

**Comment by fpillet** [comment]
Safari won't ever work on Windows for the Android version, you'll have to stick with Chrome (reason is, Safari on Windows only uses the old websocket draft, our handwritten implementation in the Android version only supports the final standard)

**Comment by MichaelHartmann** [comment]
Hello Pillet

I was on vacation so I can not answer right now.
Unfortunately, it still does not work for.
Mine environments:
Windows 7
Google Chrome: 21.0.1180.89
Android: 2.3.6
Mobile: Samsung I9001XXKPK

Here are two pictures:
Debuging with OS51.1 and Safari
Debuging with Android and Google Chrome.

What conspicuous that, according not the message "caching completed in xxms" comes.

Regards
Michael
