### ISSUE TITLE
ChangeIP address for sytems don't work.

### ISSUE THREAD

**Issue by sdomotica** [CommandFusion/iViewer-For-Android#69]
If I try to change some systems  IP address trought CF.setSystemProperties, it don't work.
Bye
Sandro

**Comment by fpillet** [comment]
Can you show the code you are using? I just retested build 96 and it works fine - changing the port and / or IP address both work fine.

**Comment by fpillet** [comment]
Also, please details (with every bug report so I don't waste time digging) which version of Android you are running, which hardware model, etc
