### ISSUE TITLE
Command (IR code) works on Ipad but not on Android device (Samsung S3)

### ISSUE THREAD

**Issue by geoffbrain** [CommandFusion/iViewer-For-Android#70]
I am not sure this is a bug but I found a discrepancy between the gui files parsing on the Ipad compared to Android device.

On the IPAD 2 the foxtel command "Planner" worked just fine however on the Samsung S3 (Android™ 4.0, Ice Cream Sandwich) it does nothing.  All other 40-50 foxtel commands work just fine.

The command is:
<cmd name="Foxtel Planner ">sendir,4:1,30,36000,1,1,15,10,6,10,6,22,6,10,6,16,6,22,6,22,6,10,6,10,6,10,6,22,6,16,6,22,6,28,6,28,6,16,6,10,6,3204\x0D</cmd>

The above command works on the Ipad but not the Android.

The error is the space and the end "Foxtel Planner "

If I remove this space the command works on both the Ipad and the Android.

By the way all other function on the Samsung S3 work fine other than some of the images are a little out but this is expected as the screen sizes are slightly different.

**Comment by geoffbrain** [comment]
Just read my issue above and the command does not seem to have posted correctly so here it is:

The command not accepted by the Android 

```
  <cmd name="Foxtel Planner ">sendir,4:1,30,36000,1,1,15,10,6,10,6,22,6,10,6,16,6,22,6,22,6,10,6,10,6,10,6,22,6,16,6,22,6,28,6,28,6,16,6,10,6,3204\x0D</cmd>
```

The command accepted by the Android 

```
  <cmd name="Foxtel Planner">sendir,4:1,30,36000,1,1,15,10,6,10,6,22,6,10,6,16,6,22,6,22,6,10,6,10,6,10,6,22,6,16,6,22,6,28,6,28,6,16,6,10,6,3204\x0D</cmd>
```

**Comment by geoffbrain** [comment]
Hope this makes sense

**Comment by fpillet** [comment]
Thanks for the report, Geoff. Working on the issues list, we'll get on your bug soon. I think there is a relationship between this and another issue, this is being investigated.

**Comment by geoffbrain** [comment]
No hurry.  The problem still exists but I can't be sure what the issue only
that it does exist.  Easy to repeat but had to figure out any scenarios
where it does not occur.  To resolve mean killing the app in both devices
then restarting iviewer in the one I want to use.  Cheers.

p.s. anything I can do to help please ask

Regards,

Geoff Brain

 Phone: 61-7-3032-6030 | Mobile: 61-412-207-560 |                                     a 
 Home: 61-7-5526-8857  
 E-mail: brain@au1.ibm.com

**Comment by geoffbrain** [comment]
Issue can be fixed by correct coding all be it not in the intended way.
