### ISSUE TITLE
Ipad and Samaung S3 connected at samne time lock network

### ISSUE THREAD

**Issue by geoffbrain** [CommandFusion/iViewer-For-Android#71]
I have a IPAD 2 and a Samsung S3 (Android™ 4.0, Ice Cream Sandwich).  The same app work well on both devices.

I have a bug as follows.  If I use each device on its own there are no issues.

If I use both together, when I execute a command from the Ipad then the Samsung S3 it then causes the wi-fi network to lock up such that no commands will work from either the Ipad or the Samsung S3.  If I go to the Samsung S3 Apps manager and kill (force stop) the Iviewer app the Ipad command start working again.

If do the opposite

When I execute a command from the Samsung S3 and then the Ipad it then causes the wi-fi network to lock up such that no commands will work from either the Ipad or the Samsung S3. If I go to the Ipad and kill the Iviewer app it does not unlock commands from the Samsung S3.  I have to kill the app on the Samsung to get it working again.

I would think both should work together OK.

Hope this explanation is OK.  It seems the Iviewer app on the Samsung S3 may be locking the wi0fi network somehow.

p.s. I use a icache GC-100-12

**Comment by digostos** [comment]
That is a problem he himself GC-100 does just that.
can ipad and android or ipad and ipad together, it already happened to me

**Comment by fpillet** [comment]
GlobalCaché devices allow only a single connection at a time. Your WiFi network cannot lock up because of data sent by either the iPad or Samsung app. Rather, one of the two (or maybe both) stay connected to the GlobalCaché.

Make sure you uncheck "Maintain constant connection" in your GUI's external system, so that neither the iPad not the Samsung stay connected to the GC-100

**Comment by geoffbrain** [comment]
Gotoit, thanks

Regards,

Geoff Brain

 Phone: 61-7-3032-6030 | Mobile: 61-412-207-560 |  
 Home: 61-7-5526-8857  
 E-mail: brain@au1.ibm.com

**Comment by geoffbrain** [comment]
For the record unchecking "Maintain constant connection" in the GUI's external system seems to resolve the issue.
