### ISSUE TITLE
Loading GUI issues on Android (Samsung S3)

### ISSUE THREAD

**Issue by geoffbrain** [CommandFusion/iViewer-For-Android#74]
I have had limited success using the iViewer upload facility so have been using a HTTP server.

If I load from my laptop (192.168.0.14) the first time all works fine.  I can then reload, etc.  In setup the config file address would be like http://192.168.0.14/myremote/myremote.gui.

if however the IP address of my laptop changes. (as it does when it goes from Ethernet wire to WIFI 192.168.0.6 or visa versa) iViewer will then no longer loads.  It hangs during the startup and load process.  Any attempt to enter the setup area result in iViewer crashing - you have some automatic logs/dumps from me re: this issues.  SO I cannot change the config file address to http://192.168.0.6/myremote/myremote.gui.

If I force stop on the Android of iViewer it does not fix the problem.

I have to either re-install iViewer or change my laptop address back to 192.168.0.14.

Interesting.

p.s. In setup selecting reload gui has the same result.

**Comment by fpillet** [comment]
Hi Geoff, very interesting report indeed. I'll make a change to directly open the settings when a GUI file cannot be loaded.

**Comment by geoffbrain** [comment]
That would be great, thanks.   I assume that will be in the next Beta
release - by the way how do we know when this occurs?

**Comment by fpillet** [comment]
I'll make an announcement on the Google group. Right now I'm troubleshooting some orientation issue, I have fixed several issues already. New release maybe today or over the w-e.

**Comment by fpillet** [comment]
This should be fixed with beta release 101. Please install it and close this bug if it is fixed for you (link to beta is in the Release notes document as usual)

**Comment by fpillet** [comment]
Actually I bumped to build #102 to fix another issue.

**Comment by geoffbrain** [comment]
Loading GUI appears to now work using the Guidesigner upload feature and using FTP server on laptop.

Also it appears all images uploaded more consistently - no missing images so far.  Big improvement.

Also starting Iviwer on the Android seems to be more consistent - nor errors so far.

Also in beta 96 the suppression of key clicks did not work, it now work on Beta 102.

If I see anything I'll raise an issue.  Great work.
