### ISSUE TITLE
version 100 and 102 don't load javascript

### ISSUE THREAD

**Issue by sdomotica** [CommandFusion/iViewer-For-Android#75]
The newest version don't load javascript module.
Use the my test project sent you to see the error in debugger.

As usual Galaxy Tab 10.1 running android 4.0.4

Bye
Sandro

**Comment by curtdwar** [comment]
I'm also having issues loading Javascript modules into the javascript debugger. I've tested it on the following and get a "Forbidden" message in all setups. 

remoteiviewer.js does load, but no modules loaded through the project sript manager in guidesigner are accessable in the debugger.

Windows7: Chrome 21.0.1180.89 m
Mac OSX Lion 10.7.4: Safari 6.0 (7536.25)
Mac OSX Lion 10.7.4: Chrome 21.0.1180.89

**Comment by fpillet** [comment]
Okay guys think there are still a couple places where I messed up - I made a pretty radical change to fix issue with Android 4.x and this broke some parts of the debugger. Next update very soon, thanks for the reports

**Comment by fpillet** [comment]
I have fixed an issue that was preventing JavaScript from running properly without the Remote Debugger connected (check build #103)

**Comment by sdomotica** [comment]
Thanks a lot. Now working fine. Galaxy Tab 10.1 running 4.0.4
Bye
Sandro

**Comment by curtdwar** [comment]
With or without the debugger running I still have no javascript working in Jellybean on Nexus7 or ICS 4.0.3 on OneXL. When loading with the debugger I get forbidden 403 messages.
