### ISSUE TITLE
Not loading gui assets

### ISSUE THREAD

**Issue by tonymarstin** [CommandFusion/iViewer-For-Android#78]
HI Just got a galaxy note 2 and my demo code - using a gui from an ipad the basic screen loads but not button graphics.
Tried to load as a zip file and it just fails with the message the gui at <unknown> failed loading.
Error: Failed unzipping test.gui.zip.

Any thoughts?

Thanks

Tony

**Comment by tonymarstin** [comment]
I've done some more testing and it looks like a DNS error of some kind - if i use the upload service and an ip address it loads fine & seems to work ok, except for udp multicast not being matched.

**Comment by tonymarstin** [comment]
Pressed the wrong button!

**Comment by fpillet** [comment]
Can you give us more information about this issue? In particular, I'm interested in seeing a test GUI (for example, a minimal version of your GUI) that fails loading under specific conditions. Any extended information you can provide will help resolving this issue. Thanks!
