### ISSUE TITLE
iViewer 103, javascript and remote debugger

### ISSUE THREAD

**Issue by RichardMullins** [CommandFusion/iViewer-For-Android#79]
I am having problems with the remote debugger under 103, similar to the issues found in 100 and 102.

The javascript code works perfectly when the remote debugger is turned off. If I turn it on however the javascript code does not run.

The remote debugger  does work correctly, remoteviewer.js loads correctly and shows join changes from gestures (although not from button presses - not sure if that is normal or not).

The javascript code that I have loaded (CIPV1.1 and a config.js that I use for my CF.userMain()) is shown as 403 forbidden. I have tried in Chrome and Safari (on a Mac) although I imagine this is an issue with the code on the device, not something related to the browser.

I checked file permissions just in case (nothing obvious) but this code _does_ run when I don't use the debugger so I'm guessing thats not the issue.

rich

**Comment by RichardMullins** [comment]
Sorry, forgot to mention I'm running on a Nexus7, Android Jelly Bean (4.1.2) and as the title implies running beta103 of iViewer. 

rich

**Comment by curtdwar** [comment]
Interesting that you have working javascript when debugger not loaded. I also have nexus7 same software versions as you and I am unable to get any javascript working at all. There hasn't been an update on the previous thread for this issue in over a month, hopefully Florent will make a breakthrough soon.

**Comment by n2hifi** [comment]
I'm seeing the same thing as Rich.  Nexus7, Jelly Bean and javascript works as long as debugger is off.

**Comment by fpillet** [comment]
Sorry guys we haven't let you down, just been busy coping with iOS 6 on iPad / iPhone.

Is there anything special with your GUI setup? for example, do you use a separate subfolder for assets where JavaScript code would be stored?

**Comment by n2hifi** [comment]
I found if I have Javascript in a subfolder it does not work at all.  I had to put it at the root to get it to work.

**Comment by fpillet** [comment]
This makes a lot of sense! Issue will be fixed in the next build, coming up shortly.

**Comment by RichardMullins** [comment]
In my case I don't have any sub-folders. The javascript does run correctly when I turn off the debugger, but with the debugger on my scripts show up with a 403 forbidden message in the console.

**Comment by curtdwar** [comment]
Thanks, that got me working in JS again.

**Comment by fpillet** [comment]
Richard, is there anything else special with your JS files? For example, spaces in the names, etc?

**Comment by RichardMullins** [comment]
Florent,

No nothing unusual. The two files are CIPV1.1.js (the one from github - unmodified with the exception of pulling out the userMain section) and a config.js that essentially just pulls out the userMain (at the time of testing it only has the Crestron setup stuff from the CIPV1.1 in it).

The setup works as expected if the debugger is off, with correct connection through to my Crestron processor. I added a weather script over the weekend and that worked OK as well (with the debugger off).

**Comment by fpillet** [comment]
Richard, would you mind emailing me your project so I can try here and wee what's wrong? I have no clue about your specific problem at this point, but having the project handy should help.

**Comment by fpillet** [comment]
No need to send us your GUI, the issue has been identified. Thanks to all for helping nail this one.
