### ISSUE TITLE
Subpages transition in on each page load. But should only happen when join state changes.

### ISSUE THREAD

**Issue by jarrodbell** [CommandFusion/iViewer-For-Android#8]
When a subpage is shown on a page flip, it always transitions in. This should not happen.

Instead, subpages should only transition when their digital join changes state.

**Comment by ucbrasil** [comment]
I don´t know if it is the same problem, but in my case, when I call a new subpage, the old one doesn´t disapear (made with a macro that set one digital join to 1 and the others to 0). I used as a test a project that works good on iPhone. 
Phone: Galaxy Android V2.3.4 user:automacao@uc-brasil.com (at the moment without a license)

**Comment by jarrodbell** [comment]
Not related. Please create a new issue and link us to a GUI archive with a test case.

Please make sure all test cases only contain enough information to replicate the issue. Large test GUIs make it harder to find the issue - unless of course the issue cannot be replicated in a small GUI.

**Comment by fpillet** [comment]
Case closed, invalid issue
