### ISSUE TITLE
Random graphics missing

### ISSUE THREAD

**Issue by n2hifi** [CommandFusion/iViewer-For-Android#80]
I have two related things going on here. 

FIrst, I have a page of graphic assets that are assigned to particular images via javascript (weather icons)  All of the assets show on the reference page full of images so I know they are loading, however  they randomly show on my weather page.  Like three out of five show randomly and it changes.  Everything works fine when I first upload but it seems to degrade over time like a memory leak. I would chalk this off to a javascript error if it weren't for the second issue...

Several of my subpages are randomly missing graphics as well.  These are static graphics and not called by javascript.  If I reload they all come back for awhile.  In GUI options I have the first two boxes unchecked and the rest checked.  I was hoping to get a little further in troubleshooting before posting so sorry I don't have more details.  I am continuing to look for a pattern.

Google Nexus7
JellyBean 4.2

**Comment by fpillet** [comment]
Thanks for the report! Would you mind emailing me your project? With the issue on sight we may be able to quickly identify it.

**Comment by n2hifi** [comment]
Mark (molsen@cignalsys.com) wants to share some files with you using Dropbox. Message from Mark:

"I zipped it but it was still 40MB and was rejected by the mail server so I dropped it in my dropbox account.  This e-mail should provide you a link.

It first starts happening on the weather subpage (if you swipe right you get a larger, detailed forecast).  Sometimes it’s the weather icons called by JS but often it is the backgrounds that are just static.  The worst it has been, the images on the lighting control subpage (flyout) start to disappear.  My latest suspicion is it starts to happen when I move from one network to another but I cannot confirm that.

Mark Olsen, CTS
Design Engineering
Cignal Systems, Inc.
"

View the "Command Fusion" folder here: https://www.dropbox.com/el/?r=/link/17.znCdFCpQTp%3Fk%3D9rfNA-ZflUtnLQsOiBHL8bwmjqdpQrI1%26eh%3DAAAMNFBTzXfwPhy9uf6QruGbPpSuKCTM8vAGcSly3Kj-7w&b=clk:None:14967144353079941956:735:415&z=AACme36AFYnDaFozcIMmxjvt-inmYthz0aDlXjlg8BbHOg

Enjoy!
- The Dropbox Team

**Comment by fpillet** [comment]
Thanks, Mark!

I have an open bug where comms stop when switching networks, so you may very well be onto something related. Thanks a lot for the time you took reporting this!

Florent

On Nov 20, 2012, at 3:22 PM, n2hifi notifications@github.com wrote:

> Mark (molsen@cignalsys.com) wants to share some files with you using Dropbox. Message from Mark:
> 
> "I zipped it but it was still 40MB and was rejected by the mail server so I dropped it in my dropbox account. This e-mail should provide you a link.
> 
> It first starts happening on the weather subpage (if you swipe right you get a larger, detailed forecast). Sometimes it’s the weather icons called by JS but often it is the backgrounds that are just static. The worst it has been, the images on the lighting control subpage (flyout) start to disappear. My latest suspicion is it starts to happen when I move from one network to another but I cannot confirm that.
> 
> Mark Olsen, CTS
> Design Engineering
> Cignal Systems, Inc.
> "
> 
> View the "Command Fusion" folder here: https://www.dropbox.com/el/?r=/link/17.znCdFCpQTp%3Fk%3D9rfNA-ZflUtnLQsOiBHL8bwmjqdpQrI1%26eh%3DAAAMNFBTzXfwPhy9uf6QruGbPpSuKCTM8vAGcSly3Kj-7w&b=clk:None:14967144353079941956:735:415&z=AACme36AFYnDaFozcIMmxjvt-inmYthz0aDlXjlg8BbHOg
> 
> Enjoy!
> - The Dropbox Team
>   —
>   Reply to this email directly or view it on GitHub.

## 

Florent Pillet - Software Engineering Lead
www.commandfusion.com

**Comment by fpillet** [comment]
Mark, can you try with the latest build? A number of networking-related issues were solved in this build.

**Comment by n2hifi** [comment]
Just a quick note.  It doesn't appear to have been resolved.  Now that I can do debugging with JS I will make sure it's not in the coding, but I have a deadline tomorrow so it will have to wait a day or two.

**Comment by curtdwar** [comment]
I have noticed that images on subpages are not caching unless the subpage is opened while uploader is running.

I can reproduce this 100% of the time.

start uploader, launch iviewer, once caching is complete, close uploader.
open subpage and the images will be missing their attached graphic.

if I open each subpage before I close the uploader then all images will load after 1/2 a second or so.

**Comment by n2hifi** [comment]
So when the image doesn't load, it appears it doesn't load the image placeholder which breaks the join to that placeholder.  Therefore even though I assign my images dynamically in Javascript they don't show up in spite of being visible on the page they are referenced from.  It makes sense now and explains what before seemed psudo random.  I can reproduce this as well.

**Comment by n2hifi** [comment]
Scratch that.  I was referencing images from the wrong place so the placeholder thing may be incorrect.  I can reproduce the subpage caching though.

**Comment by n2hifi** [comment]
So before I confirm or deny I don't know what I am doing.  Maybe someone can answer a question. 

If I reference an image on a standard page say Image1.png iViewer should cache that image, correct?  Now if I do a serial join in Javascript 
CF.setJoin("s123","Image1.png")
that image should be cached and therefore display correct?  Or do I need to reference those images a different way in Javascript?
Sorry for asking a tech support question in the beta forum but it seemed the quickest way to get the the heart of this issue.

**Comment by fpillet** [comment]
That's fine. So yes, basically if caching is enabled on the image in guiDesigner, then yes a second image using the same reference will pull the file from the cache.

**Comment by n2hifi** [comment]
With beta 113 it appears the caching of subpage images issue is better but not completely fixed. iViewer does not cache images on a subpage if they are referenced from another page with CF.setJoin().  If I leave GUIdesigner upload sevice on and open a subpage that uses CF.setJoin() everything is visible but if I stop the upload service before opening the subpage any image set using CF.setJoin() does not appear.

**Comment by fpillet** [comment]
This cache preload thing has been fixed. Thanks!
