### ISSUE TITLE
Waiting for Remote Debugger window not always clearing

### ISSUE THREAD

**Issue by DevinCook** [CommandFusion/iViewer-For-Android#83]
Using Beta 1.05
  I could connect with the debugger and it seemed to be active, but the window did not close.

This seems better now, not sure how to retrigger the issue.

This is on a Nexus 7.

**Comment by fpillet** [comment]
Happened only once? Meaning that you never saw it again? now that is weird. thanks for updating this issue if you see it again.

**Comment by DevinCook** [comment]
Haven't seen the issue in the latest betas
