### ISSUE TITLE
First list item not updating properly

### ISSUE THREAD

**Issue by DevinCook** [CommandFusion/iViewer-For-Android#84]
Ok,

I appears the first item added to list is drawing before it's strings are initialized.  After scrolling down and back to the top it appears correctly.

**Comment by fpillet** [comment]
Does this happen with build #105 that has been released this week? The list refresh issue is an issue that has specifically been handled in this one, so if you're still seeing it we'd like to get our hands on your GUI to investigate.

**Comment by DevinCook** [comment]
From the debugger:

> Javascript starting up. iViewer version: 1.0 (#105-a116da3)

Here is the demo gui.  It seems to happen on the first fill.  Press Setup List a few times to add items and you should see the top item sub added but string not filled or filled improperly.

After there are enough items to allow scrolling, you can fix the issue by scrolling down and back.

**Comment by DevinCook** [comment]
With further testing I discovered:

```
self.buildList = function() {
    CF.listRemove('l100');
    CF.listAdd("l100", [{s1: "Item 1a",s2: "Item 1b",},]);
    CF.listAdd("l100", [{s1: "Item 2a",s2: "Item 2b",},]);
    CF.listAdd("l100", [{s1: "Item 3a",s2: "Item 3b",},]);
    CF.listAdd("l100", [{s1: "Item 4a",s2: "Item 4b",},]);
};
```

When I run this code it clears the list, but on Android I get 4a,4b, 1a,1b, 2a,2b, 3a,3b.

On iViewer Next I get the expected result.

**Comment by fpillet** [comment]
Issue fixed for next build. Thanks a lot for reporting it!
