### ISSUE TITLE
Javascript debugging issues with Javascript Console (using Chrome / Windows)

### ISSUE THREAD

**Issue by DevinCook** [CommandFusion/iViewer-For-Android#85]
If I attach the remote debugger and try to interact with the Android viewer I don't see any affect.

Trying it with iViewer Next on an iPad worked.

I tried CF.setJoint and CF.listRemove with similar results.

**Comment by fpillet** [comment]
Please try with new build #107, we checked this again and it seems to work fine.

For example, connect to a GUI, fire up the JS console in Chrome and type: CF.setJoin("s0", "test");

Now all your buttons and labels on s0 should display "test".

**Comment by DevinCook** [comment]
Seems fixed with 107.
