### ISSUE TITLE
List Image URL's with username:password

### ISSUE THREAD

**Issue by curtdwar** [CommandFusion/iViewer-For-Android#86]
I noticed when using the XBMC sample GUI that lists with images sourced from the XBMC webserver were not displaying.

Turns out the issue is with the username and password.

> http://xbmc:@192.168.1.130:801/image/image%3A%2F%2Fhttp%253a%252f%252fcf2.imgobject.com%252ft%252fp%252foriginal%252f6zMUhU3lEMky62ghhbFXLEsbI6K.jpg%2F

That image works fine in a browser window, but does not display in Iviewer. If I remove the "XBMC:@" it displays fine.

Not sure if the problem is the lack of password (which I have set as null) or if it's the entire username:password@ that is the issue.

**Comment by fpillet** [comment]
I think this is the authentication thing - Android still has some issue downloading data from authenticated connections. We'll update the software shortly with a fix.

**Comment by fpillet** [comment]
Fixed for next build.
