### ISSUE TITLE
Not Connecting to Network - Nexus 10

### ISSUE THREAD

**Issue by dbetts** [CommandFusion/iViewer-For-Android#89]
I brought the XBMC application from GitHub directly onto the GUI Designer and added a Nexus 10 and the iPad devices to the application. I then loaded the same application onto the iPad 3 and the Nexus 10.

It works great in the iPad, but I'm getting a connection type of error:  "SCRIPT: ERROR REPLY --------" message in the debugger for the Nexus 10 Android.

I spoke with Jarrod about it on Skype and he believes it is an issue with the global tokens not being  correctly accessed in the Android.

**Comment by dbetts** [comment]
Same problem on Beta Build 113 (January 30, 2013) - no connection.

**Comment by fpillet** [comment]
Thanks for the update. Do you still have the same problem with the just-released build 122? 

We have seen a number of crashes coming from a Nexus 10, going to investigate them to provide additional bug fixes.

**Comment by edwardbritt** [comment]
Problem solved in build #122.  Nice work!

**Comment by dbetts** [comment]
Problem solved.
