### ISSUE TITLE
Subpage transition "moveIn" "fromRight" moves in from left.

### ISSUE THREAD

**Issue by jarrodbell** [CommandFusion/iViewer-For-Android#9]
When subpage transition is defined as "MoveIn" subtype "fromRight", it actually comes in from the left of screen.

Changing it to "fromLeft" has no affect - subpage still comes in from left of screen.

**Comment by fpillet** [comment]
Can't reproduce with latest build on either Kindle Fire nor Acer 3.x

**Comment by jarrodbell** [comment]
This was due to subpage transition not finished from "hiding" the subpage before "showing" it again. Which is correct behaviour.
