### ISSUE TITLE
HTC Sensation does not seem to respond to any button pushing

### ISSUE THREAD

**Issue by eferkr** [CommandFusion/iViewer-For-Android#90]
I installed the Beta on HTC Sensation and do not get any response from the pressing of buttons.

**Comment by fpillet** [comment]
Are your buttons in simulated mode? if no, are you connected to a control system that sends back the pressed state of the buttons?

**Comment by eferkr** [comment]
they are indeed in Simulated mode. I will check it out. Thanks Florent.

**Comment by eferkr** [comment]
Florian. I checked and the buttons are on simulated feedback. No system state feedback. I control Arduino with CF-Send command and 3 letter combination to control remote switches with 433 mhz transmitter.
On Ipad the GUI works fine but on Android no response.

**Comment by fpillet** [comment]
Okay we're progressing. Now can you tell me how the system used to talk to the Arduino device is defined? is it TCP or UDP, which port is it using, etc?

**Comment by eferkr** [comment]
UDP on port 85 on Arduino

**Comment by fpillet** [comment]
Okay so this may be a UDP issue. We'll release an update this week that fixes some UDP issues, it will possibly solve your problem.

**Comment by eferkr** [comment]
Great,

I will keep you posted on this ISSUE after I test the update.

Thanks, Erik

**Comment by eferkr** [comment]
thanks for the help.

Great system by the way.
