### ISSUE TITLE
Sonos discovery does not work with latest Sonos module

### ISSUE THREAD

**Issue by xAPPO** [CommandFusion/iViewer-For-Android#91]
I suspect this is the same issue that was recently fixed in iOS (testflight) but the Sonos auto discovery isn't working.

K

**Comment by fpillet** [comment]
If the Sonos module uses Bonjour to discover services this is normal - Bonjour support is not implemented on Android yet. Otherwise, yes pretty much the same issue has been fixed on Android.

**Comment by fpillet** [comment]
Have you tried build 113 ?

**Comment by jarrodbell** [comment]
FYI - Sonos discovery doesn't use Bonjour. It's using DLNA/UPnP packets, UDP Multicasting and Broadcasting.
