### ISSUE TITLE
IViewer Crash

### ISSUE THREAD

**Issue by curtdwar** [CommandFusion/iViewer-For-Android#93]
I'm getting a consistant crash since updating to 113. I've done all I can to identify the issue. I have a couple subpages, only one is causing the crash. 100% of the time when i close a particular subpage the app crashes. I cannot find anywhere that this subpage has different settings or code than the other pages that do not crash. Nothing is being identified in the Debug log.

Nexus 7, Android 4.2.1

Logcat
http://pastebin.com/UeqPPdAH

**Comment by fpillet** [comment]
Thanks, we've seen the crash too. The issue has been fixed here, a new Android build will be released over the week-end. Thanks for reporting!

PS: yes there is a stack trace in the debug log, think you missed it because the names are mangled, but it's there :-)

**Comment by fpillet** [comment]
Fixed for next build
