### ISSUE TITLE
Host Name

### ISSUE THREAD

**Issue by MichaelHartmann** [CommandFusion/iViewer-For-Android#95]
When I use the guide designers in the System Properties in the IP Address / Host Name "name.dyndns.org" enter, then the iPad is the IP telegram "standard query a name.dyndns.org" sent. And there is an appropriate response. With Android is not the case.

**Comment by fpillet** [comment]
Thanks for the report. Can you list the settings you are using for this system? Ideally, copy-paste here the XML line that defines the system (<system name="...") in your GUI file. This will help reproduce and troubleshoot the issue. We have been using canonical names (DNS queries) and Android and they have been working fine, so also feel free to precisely describe your device (model, OS version) and network setup so we can thoroughly analyze the issue.

**Comment by MichaelHartmann** [comment]
<systems>
    <system name="KNXnetIP" ip="wischenhofen.mine.nu" origin="54321" port="3671" protocol="udp" alwayson="1" offlinequeue="1" accept="0" acceptBroadcasts="0" ssl="0" maxconnections="0" heartbeatRx="" heartbeatTx="" heartbeatMode="0" eom="" connectionStatus="0" disconnectionStatus="0">

**Comment by MichaelHartmann** [comment]
<systems>
    <system name="KNXnetIP" ip="wischenhofen.mine.nu" origin="54321" port="3671" protocol="udp" alwayson="1" offlinequeue="1" accept="0" acceptBroadcasts="0" ssl="0" maxconnections="0" heartbeatRx="" heartbeatTx="" heartbeatMode="0" eom="" connectionStatus="0" disconnectionStatus="0">
